CREACION DE BASE DE DATOS DE MUSIC STREAM

In [ ]:
#Librerías
import requests
import json
import pandas as pd
import mysql.connector
from mysql.connector import errorcode
from sqlalchemy import create_engine

In [ ]:
#Reemplazar clave de acceso a MySQL
PWD_SQL = 'INGRESA ACÁ TU CLAVE'

In [ ]:
#Conexión con MySQL
cnx = mysql.connector.connect(user='root', password=PWD_SQL,
                              host='127.0.0.1')

#Creación de BBDD
mycursor = cnx.cursor()
try:
    mycursor.execute("CREATE DATABASE BBDD_MUSIC_STREAM")
    print(mycursor)
except mysql.connector.Error as err:
    print(err)
    print("Error Code:", err.errno)
    print("SQLSTATE", err.sqlstate)
    print("Message", err.msg)

CREACIÓN DE DATA FRAMES PARA EXPORTAR A MYSQL

In [217]:
#Creación de Data Frame consulta API DEEZER
df_songs = pd.read_csv("songs.csv") #se elimina el index_col=0 porque con el merge la primer columna se vuelve indice y no la toma. se perdía el dato artis_id
df_songs

,artist_id,artist_name,track_title,album_title,track_type,release_year,genre,genre_id
0,12246,Taylor Swift,The Fate of Ophelia,The Life of a Showgirl,solo,2025,Pop,132
1,12246,Taylor Swift,Opalite,The Life of a Showgirl,solo,2025,Pop,132
2,12246,Taylor Swift,Elizabeth Taylor,The Life of a Showgirl,solo,2025,Pop,132
3,12246,Taylor Swift,Blank Space,1989 (Deluxe),solo,2014,Pop,132
4,12246,Taylor Swift,Out Of The Woods (Taylor's Version),1989 (Taylor's Version),solo,2023,Pop,132
...,...,...,...,...,...,...,...,...
1495,61094422,Emilia,Uno los Dos,Uno los Dos,collab,2023,Pop,132
1496,61094422,Emilia,Diva (feat. Emilia),Diva (feat. Emilia),collab,2022,Rap/Hip Hop,116
1497,61094422,Emilia,Guerrero.mp3,Guerrero.mp3,solo,2023,Pop,132
1498,61094422,Emilia,Somos Más,Somos Más,collab,2026,Pop,132
1499,61094422,Emilia,Maldita Noche En Vivo,Maldita Noche,solo,2025,Pop,132

In [183]:
#Creación de Data Frame de Tabla Maestra Artistas
lista_artistas=["Taylor Swift", "Drake", "Morgan Wallen", "Kendrick Lamar", "The Weeknd",
    "SZA", "Zach Bryan", "Tyler the Creator", "Billie Eilish", "Ariana Grande", "Bad Bunny", 
    "Karol G", "Myke Towers", "Quevedo", "Aitana","Rosalía", "Morad", "Melendi", "Enrique Iglesias",
    "Juanes", "Duki", "María Becerra", "Tini Stoessel", "Nicki Nicole", "Cazzu","Lali", 
    "Paulo Londra", "Shakira", "Bizarrap", "Emilia"]

df_artistas = pd.DataFrame({'artista': lista_artistas})
df_artistas.insert(0, 'id_artista', range(1, len(df_artistas)+1))
df_artistas

    id_artista            artista
0            1       Taylor Swift
1            2              Drake
2            3      Morgan Wallen
3            4     Kendrick Lamar
4            5         The Weeknd
5            6                SZA
6            7         Zach Bryan
7            8  Tyler the Creator
8            9      Billie Eilish
9           10      Ariana Grande
10          11          Bad Bunny
11          12            Karol G
12          13        Myke Towers
13          14            Quevedo
14          15             Aitana
15          16            Rosalía
16          17              Morad
17          18            Melendi
18          19   Enrique Iglesias
19          20             Juanes
20          21               Duki
21          22      María Becerra
22          23      Tini Stoessel
23          24       Nicki Nicole
24          25              Cazzu
25          26               Lali
26          27       Paulo Londra
27          28            Shakira
28          29           Bizarrap
29          30             Emilia

NORMALIZACIÓN

In [184]:
import re
import unicodedata

def normalizar(texto):
    if not isinstance(texto, str):
        return ''
    texto = texto.lower().strip()
    # Eliminar acentos
    texto = ''.join(c for c in unicodedata.normalize('NFD', texto)
                    if unicodedata.category(c) != 'Mn')
    # Eliminar todo lo que NO sea letra, número o espacio (esto quita comas, puntos, etc.)
    texto = re.sub(r'[^a-z0-9\s]', '', texto)
    # Reemplazar múltiples espacios por uno solo
    texto = re.sub(r'\s+', ' ', texto).strip()
    return texto

NORMALIZACION Y MERGE API DEEZER Y TABLA MAESTRA DE ARTISTAS

In [218]:
#Importacion de archivo .csv
df_songs = pd.read_csv("songs.csv") #se elimina el index_col=0 porque con el merge la primer columna se vuelve indice y no la toma. se perdía el dato artis_id
#Normalización de frames antes del merge
#Deezer
df_songs['norm'] = df_songs['artist_name'].apply(normalizar)
#Tabla Maestra
df_artistas['norm'] = df_artistas['artista'].apply(normalizar)

In [219]:
# Merge: conservar filas donde el nombre normalizado coincida
df_songs=df_songs.merge(df_artistas[['norm', 'id_artista']], on='norm', how='inner')

# Limpiar columna temporal 'norm'
df_songs.drop(columns=['norm'], inplace=True)

# Reordenar columnas
df_songs = df_songs[['id_artista','artist_id','artist_name', 'track_title', 'album_title','track_type','release_year','genre_id','genre']]

In [220]:
print(f"Filas después del merge: {len(df_songs)}")         
print("Artistas únicos:", df_songs['artist_name'].nunique())

Filas después del merge: 1500
Artistas únicos: 30

In [222]:
df_songs

,id_artista,artist_id,artist_name,track_title,album_title,track_type,release_year,genre_id,genre
0,1,12246,Taylor Swift,The Fate of Ophelia,The Life of a Showgirl,solo,2025,132,Pop
1,1,12246,Taylor Swift,Opalite,The Life of a Showgirl,solo,2025,132,Pop
2,1,12246,Taylor Swift,Elizabeth Taylor,The Life of a Showgirl,solo,2025,132,Pop
3,1,12246,Taylor Swift,Blank Space,1989 (Deluxe),solo,2014,132,Pop
4,1,12246,Taylor Swift,Out Of The Woods (Taylor's Version),1989 (Taylor's Version),solo,2023,132,Pop
...,...,...,...,...,...,...,...,...,...
1495,30,61094422,Emilia,Uno los Dos,Uno los Dos,collab,2023,132,Pop
1496,30,61094422,Emilia,Diva (feat. Emilia),Diva (feat. Emilia),collab,2022,116,Rap/Hip Hop
1497,30,61094422,Emilia,Guerrero.mp3,Guerrero.mp3,solo,2023,132,Pop
1498,30,61094422,Emilia,Somos Más,Somos Más,collab,2026,132,Pop
1499,30,61094422,Emilia,Maldita Noche En Vivo,Maldita Noche,solo,2025,132,Pop

API LASTFM

In [186]:
#TABLA STATS

#Importar archivo .csv
df_stats=pd.read_csv("artistas_stats_ratio.csv")

#Normalizar
df_stats['norm'] = df_stats['artista'].apply(normalizar)

#Merge
df_stats = df_stats.merge(df_artistas[['norm', 'id_artista']], on='norm', how='inner')
df_stats.drop(columns=['norm'], inplace=True)

# Renombrar 'artista' a 'nombre_artista' 
df_stats.rename(columns={'artista': 'nombre_artista'}, inplace=True)

# Reordenar columnas
df_stats = df_stats[['id_artista', 'nombre_artista', 'n_oyentes', 'n_playcount', 'ratio_popularidad']]

print("Estadísticas listas:", df_stats.shape)

Estadísticas listas: (30, 5)

In [192]:
df_stats

    id_artista     nombre_artista  n_oyentes  n_playcount  ratio_popularidad
0            1       Taylor Swift    5948967   3683614785         619.202424
1            2              Drake    6729727   1169696541         173.810400
2            3      Morgan Wallen     989113     91888417          92.899817
3            4     Kendrick Lamar    5106415   1033716569         202.434892
4            5         The Weeknd    5328245   1126305806         211.384012
5            6                SZA    3504094    589255295         168.161954
6            7         Zach Bryan    1208397    137124086         113.476023
7            8  Tyler the Creator     107186      2735055          25.516905
8            9      Billie Eilish    4239357    838620840         197.817933
9           10      Ariana Grande    4492745   1115822259         248.360915
10          11          Bad Bunny    2590653    408927893         157.847420
11          12            Karol G    1451485     76292593          52.561751
12          13        Myke Towers     661720     28597446          43.216838
13          14            Quevedo     387739     23975059          61.832983
14          15             Aitana     245120     14890195          60.746553
15          16            Rosalía    1871616    204488926         109.257949
16          17              Morad     207877      9355983          45.007302
17          18            Melendi     316407      8249876          26.073620
18          19   Enrique Iglesias    2716934     54327654          19.995942
19          20             Juanes    1211159     22001553          18.165702
20          21               Duki     298789     43159159         144.446948
21          22      María Becerra        511         7104          13.902153
22          23      Tini Stoessel         49          486           9.918367
23          24       Nicki Nicole     257566     10863954          42.179302
24          25              Cazzu     208180      5902008          28.350504
25          26               Lali     133198      9023208          67.742819
26          27       Paulo Londra     388136     16810457          43.310739
27          28            Shakira    4890728    180830063          36.974058
28          29           Bizarrap     929562     46103038          49.596517
29          30             Emilia     502388     18981614          37.782777

In [ ]:
#TABLA ARTISTAS_SIMILARES

#Importar archivo .csv
df_similares=pd.read_csv("artistas_similares.csv")

#Normalizar
df_similares['norm_art'] = df_similares['artista'].apply(normalizar)
df_similares['norm_sim'] = df_similares['similar'].apply(normalizar) 

# Merge para artista principal (inner porque debe estar en la lista)
df_similares = df_similares.merge(df_artistas[['norm', 'id_artista']], left_on='norm_art', right_on='norm', how='inner')
df_similares.rename(columns={'id_artista': 'id_artista_principal'}, inplace=True)

# Merge para similar (left join, puede no estar en la lista)
df_similares = df_similares.merge(df_artistas[['norm', 'id_artista']],left_on='norm_sim', right_on='norm', how='left')
df_similares.rename(columns={'id_artista': 'id_artista_similar'}, inplace=True)

# Renombrar 'artista' a 'nombre_artista'
df_similares.rename(columns={'artista': 'nombre_artista', 'similar': 'nombre_artista_similar'}, inplace=True)

# Limpiar columnas temporales
df_similares.drop(columns=['norm_art', 'norm_sim', 'norm_x', 'norm_y'], inplace=True, errors='ignore')

# Reordenar columnas
df_similares=df_similares[['id_artista_principal','nombre_artista','id_artista_similar','nombre_artista_similar']]

print("Similares listos:", df_similares.shape)

Similares listos: (2911, 4)

In [201]:
df_similares

,id_artista_principal,nombre_artista,id_artista_similar,nombre_artista_similar
0,1,Taylor Swift,NaN,Sabrina Carpenter
1,1,Taylor Swift,NaN,Olivia Rodrigo
2,1,Taylor Swift,NaN,Gracie Abrams
3,1,Taylor Swift,NaN,Harry Styles
4,1,Taylor Swift,NaN,Chappell Roan
...,...,...,...,...
2906,30,Emilia,NaN,Paty Cantú
2907,30,Emilia,NaN,Paris Hilton
2908,30,Emilia,NaN,Wanessa
2909,30,Emilia,NaN,Teen Angels
2910,30,Emilia,NaN,Lauren Jauregui

In [ ]:
# TABLA TOP 50 ESPAÑA, ARGENTINA, ESTADOS UNIDOS
#Importar archivo .csv
df_top50 = pd.read_csv("top_artistas_esp_arg_usa.csv")

# Normalizar
df_top50['norm'] = df_top50['artista'].apply(normalizar)

# Left join para conservar todos los rankings (artistas fuera de la lista maestra tendrán id_artista = NULL)
df_top50 = df_top50.merge(df_artistas[['norm', 'id_artista']], on='norm', how='left')

# Convertir id_artista a Int64 (nullable integer)
df_top50['id_artista'] = df_top50['id_artista'].astype('Int64')

# Eliminar columna temporal
df_top50.drop(columns=['norm'], inplace=True)

# Renombrar 'artista' a 'nombre_artista'
df_top50.rename(columns={'artista': 'nombre_artista'}, inplace=True)

# Reordenar columnas
df_top50 = df_top50[['pais', 'ranking', 'id_artista', 'nombre_artista', 'oyentes']]

print("Top50 listo:", df_top50.shape)

Top50 listo: (150, 5)

In [213]:
df_top50     #valores <NA> migran como NULL a MYSQL

               pais  ranking  id_artista       nombre_artista  oyentes
0            España        1          11            Bad Bunny    12431
1            España        2          16              Rosalía    10254
2            España        3          14              Quevedo     8637
3            España        4        <NA>        Justin Bieber     8379
4            España        5        <NA>       Olivia Rodrigo     8227
..              ...      ...         ...                  ...      ...
145  Estados Unidos       46        <NA>              Tv Girl   125197
146  Estados Unidos       47        <NA>           Steve Lacy   123631
147  Estados Unidos       48        <NA>         Dominic Fike   121069
148  Estados Unidos       49        <NA>  Panic! At The Disco   120877
149  Estados Unidos       50        <NA>          The Strokes   120235

[150 rows x 5 columns]

CREACIÓN DE TABLAS EN MYSQL

In [214]:
# Create_engine para BBDD MusicStream

engine = create_engine(f'mysql+mysqlconnector://root:{PWD_SQL}@localhost/BBDD_MUSIC_STREAM')

In [ ]:
#Subir Tabla Maestra Artistas
df_artistas.to_sql('artistas', engine, if_exists='replace', index=False)
print("Tabla Maestra'artistas' creada.")

MIGRACIÓN DE TABLAS NORMALIZADAS

In [223]:
tablas = {
    'deezer_songs': df_songs,
    'lastfm_popularidad': df_stats,
    'lastfm_similares': df_similares,
    'lastfm_top50_pais': df_top50
}

for nombre, df in tablas.items():
    df.to_sql(nombre, engine, if_exists='replace', index=False)
    print(f"Tabla '{nombre}' subida con {len(df)} filas.")

Tabla 'deezer_songs' subida con 1500 filas.
Tabla 'lastfm_popularidad' subida con 30 filas.
Tabla 'lastfm_similares' subida con 2911 filas.
Tabla 'lastfm_top50_pais' subida con 150 filas.