## Extracción de Datos - API Deezer

#### Librerías

In [1]:
import requests
import time
import pandas as pd
import json

#### Lista de 30 artistas populares (Argentina, España y EEUU)

In [24]:
lista_artistas=[
 
    # 🇺🇸 EEUU (10)
    "Taylor Swift", "Drake", "Morgan Wallen", "Kendrick Lamar", "The Weeknd",
    "SZA", "Zach Bryan", "Tyler the Creator", "Billie Eilish", "Ariana Grande",
 
    # 🇪🇸 España (10)
    "Bad Bunny", "Karol G", "Myke Towers", "Quevedo", "Aitana",
    "Rosalía", "Morad", "Melendi", "Enrique Iglesias", "Juanes",
 
    # 🇦🇷 Argentina (10)
    "Duki", "María Becerra", "Tini Stoessel", "Nicki Nicole", "Cazzu",
    "Lali", "Paulo Londra", "Shakira", "Bizarrap", "Emilia",
]
 
print(f"Total: {len(lista_artistas)} artistas ✅")

Total: 30 artistas ✅

#### Consulta de artistas en Deezer API - se limita a 1 por existir duplicidad de ID's - RUTA:SEARCH

In [26]:
lista_artistas=[
 
    # 🇺🇸 EEUU (10)
    "Taylor Swift", "Drake", "Morgan Wallen", "Kendrick Lamar", "The Weeknd",
    "SZA", "Zach Bryan", "Tyler the Creator", "Billie Eilish", "Ariana Grande",
 
    # 🇪🇸 España (10)
    "Bad Bunny", "Karol G", "Myke Towers", "Quevedo", "Aitana",
    "Rosalía", "Morad", "Melendi", "Enrique Iglesias", "Juanes",
 
    # 🇦🇷 Argentina (10)
    "Duki", "María Becerra", "Tini Stoessel", "Nicki Nicole", "Cazzu",
    "Lali", "Paulo Londra", "Shakira", "Bizarrap", "Emilia",
]

artista_search=[]

for artista in lista_artistas:
    consulta=requests.get(f"https://api.deezer.com/search/artist?q={artista}&index=0&limit=1")
    consulta.status_code

    if consulta.status_code != 200:
        print(f"No se pudo realizar la consulta del artista: {artista}.\n Error : {consulta.status_code}") 

    datos=consulta.json()
    artista_search.append(datos['data'][0])

print(artista_search)

[{'id': 12246, 'name': 'Taylor Swift', 'link': 'https://www.deezer.com/artist/12246', 'picture': 'https://api.deezer.com/artist/12246/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/1000x1000-000000-80-0-0.jpg', 'nb_album': 124, 'nb_fan': 12518191, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/12246/top?limit=50', 'type': 'artist'}, {'id': 246791, 'name': 'Drake', 'link': 'https://www.deezer.com/artist/246791', 'picture': 'https://api.deezer.com/artist/246791/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/1000x1000-000000-80-0-0.jpg', 'nb_album': 76, 'nb_fan': 23929052, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/246791/top?limit=50', 'type': 'artist'}, {'id': 7188840, 'name': 'Morgan Wallen', 'link': 'https://www.deezer.com/artist/7188840', 'picture': 'https://api.deezer.com/artist/7188840/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/75488d12757f5809b9e6c7f53e5bb455/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/75488d12757f5809b9e6c7f53e5bb455/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/75488d12757f5809b9e6c7f53e5bb455/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/75488d12757f5809b9e6c7f53e5bb455/1000x1000-000000-80-0-0.jpg', 'nb_album': 41, 'nb_fan': 281891, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/7188840/top?limit=50', 'type': 'artist'}, {'id': 525046, 'name': 'Kendrick Lamar', 'link': 'https://www.deezer.com/artist/525046', 'picture': 'https://api.deezer.com/artist/525046/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/1000x1000-000000-80-0-0.jpg', 'nb_album': 40, 'nb_fan': 6077190, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/525046/top?limit=50', 'type': 'artist'}, {'id': 4050205, 'name': 'The Weeknd', 'link': 'https://www.deezer.com/artist/4050205', 'picture': 'https://api.deezer.com/artist/4050205/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/1000x1000-000000-80-0-0.jpg', 'nb_album': 86, 'nb_fan': 14418000, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/4050205/top?limit=50', 'type': 'artist'}, {'id': 5531258, 'name': 'SZA', 'link': 'https://www.deezer.com/artist/5531258', 'picture': 'https://api.deezer.com/artist/5531258/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/1000x1000-000000-80-0-0.jpg', 'nb_album': 40, 'nb_fan': 1282026, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/5531258/top?limit=50', 'type': 'artist'}, {'id': 71855892, 'name': 'Zach Bryan', 'link': 'https://www.deezer.com/artist/71855892', 'picture': 'https://api.deezer.com/artist/71855892/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/1000x1000-000000-80-0-0.jpg', 'nb_album': 38, 'nb_fan': 112288, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/71855892/top?limit=50', 'type': 'artist'}, {'id': 1194083, 'name': 'Tyler, The Creator', 'link': 'https://www.deezer.com/artist/1194083', 'picture': 'https://api.deezer.com/artist/1194083/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/1000x1000-000000-80-0-0.jpg', 'nb_album': 29, 'nb_fan': 1322260, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/1194083/top?limit=50', 'type': 'artist'}, {'id': 9635624, 'name': 'Billie Eilish', 'link': 'https://www.deezer.com/artist/9635624', 'picture': 'https://api.deezer.com/artist/9635624/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/1000x1000-000000-80-0-0.jpg', 'nb_album': 32, 'nb_fan': 9108220, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/9635624/top?limit=50', 'type': 'artist'}, {'id': 1562681, 'name': 'Ariana Grande', 'link': 'https://www.deezer.com/artist/1562681', 'picture': 'https://api.deezer.com/artist/1562681/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/5fcde7fde7cde95fc36d4576afcfb49f/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/5fcde7fde7cde95fc36d4576afcfb49f/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/5fcde7fde7cde95fc36d4576afcfb49f/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/5fcde7fde7cde95fc36d4576afcfb49f/1000x1000-000000-80-0-0.jpg', 'nb_album': 69, 'nb_fan': 13297621, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/1562681/top?limit=50', 'type': 'artist'}, {'id': 10583405, 'name': 'Bad Bunny', 'link': 'https://www.deezer.com/artist/10583405', 'picture': 'https://api.deezer.com/artist/10583405/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/1000x1000-000000-80-0-0.jpg', 'nb_album': 89, 'nb_fan': 7728665, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/10583405/top?limit=50', 'type': 'artist'}, {'id': 5297021, 'name': 'KAROL G', 'link': 'https://www.deezer.com/artist/5297021', 'picture': 'https://api.deezer.com/artist/5297021/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/1000x1000-000000-80-0-0.jpg', 'nb_album': 74, 'nb_fan': 3355592, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/5297021/top?limit=50', 'type': 'artist'}, {'id': 12029862, 'name': 'Myke Towers', 'link': 'https://www.deezer.com/artist/12029862', 'picture': 'https://api.deezer.com/artist/12029862/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/1000x1000-000000-80-0-0.jpg', 'nb_album': 177, 'nb_fan': 1678056, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/12029862/top?limit=50', 'type': 'artist'}, {'id': 6705223, 'name': 'Quevedo', 'link': 'https://www.deezer.com/artist/6705223', 'picture': 'https://api.deezer.com/artist/6705223/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/1000x1000-000000-80-0-0.jpg', 'nb_album': 104, 'nb_fan': 285982, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/6705223/top?limit=50', 'type': 'artist'}, {'id': 11928391, 'name': 'Aitana', 'link': 'https://www.deezer.com/artist/11928391', 'picture': 'https://api.deezer.com/artist/11928391/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/1000x1000-000000-80-0-0.jpg', 'nb_album': 58, 'nb_fan': 343216, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/11928391/top?limit=50', 'type': 'artist'}, {'id': 554792, 'name': 'ROSALÍA', 'link': 'https://www.deezer.com/artist/554792', 'picture': 'https://api.deezer.com/artist/554792/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/1000x1000-000000-80-0-0.jpg', 'nb_album': 37, 'nb_fan': 1020879, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/554792/top?limit=50', 'type': 'artist'}, {'id': 111130212, 'name': 'Morad', 'link': 'https://www.deezer.com/artist/111130212', 'picture': 'https://api.deezer.com/artist/111130212/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/1000x1000-000000-80-0-0.jpg', 'nb_album': 133, 'nb_fan': 321531, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/111130212/top?limit=50', 'type': 'artist'}, {'id': 2697, 'name': 'Melendi', 'link': 'https://www.deezer.com/artist/2697', 'picture': 'https://api.deezer.com/artist/2697/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/1000x1000-000000-80-0-0.jpg', 'nb_album': 72, 'nb_fan': 609011, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/2697/top?limit=50', 'type': 'artist'}, {'id': 2792, 'name': 'Enrique Iglesias', 'link': 'https://www.deezer.com/artist/2792', 'picture': 'https://api.deezer.com/artist/2792/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/1000x1000-000000-80-0-0.jpg', 'nb_album': 106, 'nb_fan': 5940067, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/2792/top?limit=50', 'type': 'artist'}, {'id': 70, 'name': 'Juanes', 'link': 'https://www.deezer.com/artist/70', 'picture': 'https://api.deezer.com/artist/70/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/1000x1000-000000-80-0-0.jpg', 'nb_album': 114, 'nb_fan': 1617792, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/70/top?limit=50', 'type': 'artist'}, {'id': 4902904, 'name': 'DUKI', 'link': 'https://www.deezer.com/artist/4902904', 'picture': 'https://api.deezer.com/artist/4902904/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/1000x1000-000000-80-0-0.jpg', 'nb_album': 155, 'nb_fan': 817277, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/4902904/top?limit=50', 'type': 'artist'}, {'id': 14343187, 'name': 'Maria Becerra', 'link': 'https://www.deezer.com/artist/14343187', 'picture': 'https://api.deezer.com/artist/14343187/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/1000x1000-000000-80-0-0.jpg', 'nb_album': 75, 'nb_fan': 375042, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/14343187/top?limit=50', 'type': 'artist'}, {'id': 2252591, 'name': 'TINI', 'link': 'https://www.deezer.com/artist/2252591', 'picture': 'https://api.deezer.com/artist/2252591/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/1000x1000-000000-80-0-0.jpg', 'nb_album': 79, 'nb_fan': 904927, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/2252591/top?limit=50', 'type': 'artist'}, {'id': 13299379, 'name': 'Nicki Nicole', 'link': 'https://www.deezer.com/artist/13299379', 'picture': 'https://api.deezer.com/artist/13299379/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/1000x1000-000000-80-0-0.jpg', 'nb_album': 64, 'nb_fan': 605429, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/13299379/top?limit=50', 'type': 'artist'}, {'id': 12268072, 'name': 'Cazzu', 'link': 'https://www.deezer.com/artist/12268072', 'picture': 'https://api.deezer.com/artist/12268072/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/d4cb1c4b1f2524bbf40b0fa98c77e055/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/d4cb1c4b1f2524bbf40b0fa98c77e055/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/d4cb1c4b1f2524bbf40b0fa98c77e055/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/d4cb1c4b1f2524bbf40b0fa98c77e055/1000x1000-000000-80-0-0.jpg', 'nb_album': 56, 'nb_fan': 598912, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/12268072/top?limit=50', 'type': 'artist'}, {'id': 5181388, 'name': 'Lali', 'link': 'https://www.deezer.com/artist/5181388', 'picture': 'https://api.deezer.com/artist/5181388/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/bd8e25ceb6992963bb366e84d70518a8/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/bd8e25ceb6992963bb366e84d70518a8/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/bd8e25ceb6992963bb366e84d70518a8/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/bd8e25ceb6992963bb366e84d70518a8/1000x1000-000000-80-0-0.jpg', 'nb_album': 44, 'nb_fan': 48334, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/5181388/top?limit=50', 'type': 'artist'}, {'id': 12637039, 'name': 'Paulo Londra', 'link': 'https://www.deezer.com/artist/12637039', 'picture': 'https://api.deezer.com/artist/12637039/image', 'picture_small'

In [27]:
len(artista_search)

30

In [28]:
import json
print(json.dumps(artista_search, indent=2, ensure_ascii=False))     # para ver estructura

[
  {
    "id": 12246,
    "name": "Taylor Swift",
    "link": "https://www.deezer.com/artist/12246",
    "picture": "https://api.deezer.com/artist/12246/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/1000x1000-000000-80-0-0.jpg",
    "nb_album": 124,
    "nb_fan": 12518191,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/12246/top?limit=50",
    "type": "artist"
  },
  {
    "id": 246791,
    "name": "Drake",
    "link": "https://www.deezer.com/artist/246791",
    "picture": "https://api.deezer.com/artist/246791/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/1000x1000-000000-80-0-0.jpg",
    "nb_album": 76,
    "nb_fan": 23929052,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/246791/top?limit=50",
    "type": "artist"
  },
  {
    "id": 7188840,
    "name": "Morgan Wallen",
    "link": "https://www.deezer.com/artist/7188840",
    "picture": "https://api.deezer.com/artist/7188840/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/75488d12757f5809b9e6c7f53e5bb455/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/75488d12757f5809b9e6c7f53e5bb455/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/75488d12757f5809b9e6c7f53e5bb455/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/75488d12757f5809b9e6c7f53e5bb455/1000x1000-000000-80-0-0.jpg",
    "nb_album": 41,
    "nb_fan": 281891,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/7188840/top?limit=50",
    "type": "artist"
  },
  {
    "id": 525046,
    "name": "Kendrick Lamar",
    "link": "https://www.deezer.com/artist/525046",
    "picture": "https://api.deezer.com/artist/525046/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/1000x1000-000000-80-0-0.jpg",
    "nb_album": 40,
    "nb_fan": 6077190,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/525046/top?limit=50",
    "type": "artist"
  },
  {
    "id": 4050205,
    "name": "The Weeknd",
    "link": "https://www.deezer.com/artist/4050205",
    "picture": "https://api.deezer.com/artist/4050205/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/1000x1000-000000-80-0-0.jpg",
    "nb_album": 86,
    "nb_fan": 14418000,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/4050205/top?limit=50",
    "type": "artist"
  },
  {
    "id": 5531258,
    "name": "SZA",
    "link": "https://www.deezer.com/artist/5531258",
    "picture": "https://api.deezer.com/artist/5531258/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/1000x1000-000000-80-0-0.jpg",
    "nb_album": 40,
    "nb_fan": 1282026,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/5531258/top?limit=50",
    "type": "artist"
  },
  {
    "id": 71855892,
    "name": "Zach Bryan",
    "link": "https://www.deezer.com/artist/71855892",
    "picture": "https://api.deezer.com/artist/71855892/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/1000x1000-000000-80-0-0.jpg",
    "nb_album": 38,
    "nb_fan": 112288,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/71855892/top?limit=50",
    "type": "artist"
  },
  {
    "id": 1194083,
    "name": "Tyler, The Creator",
    "link": "https://www.deezer.com/artist/1194083",
    "picture": "https://api.deezer.com/artist/1194083/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/1000x1000-000000-80-0-0.jpg",
    "nb_album": 29,
    "nb_fan": 1322260,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/1194083/top?limit=50",
    "type": "artist"
  },
  {
    "id": 9635624,
    "name": "Billie Eilish",
    "link": "https://www.deezer.com/artist/9635624",
    "picture": "https://api.deezer.com/artist/9635624/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/1000x1000-000000-80-0-0.jpg",
    "nb_album": 32,
    "nb_fan": 9108220,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/9635624/top?limit=50",
    "type": "artist"
  },
  {
    "id": 1562681,
    "name": "Ariana Grande",
    "link": "https://www.deezer.com/artist/1562681",
    "picture": "https://api.deezer.com/artist/1562681/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/5fcde7fde7cde95fc36d4576afcfb49f/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/5fcde7fde7cde95fc36d4576afcfb49f/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/5fcde7fde7cde95fc36d4576afcfb49f/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/5fcde7fde7cde95fc36d4576afcfb49f/1000x1000-000000-80-0-0.jpg",
    "nb_album": 69,
    "nb_fan": 13297621,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/1562681/top?limit=50",
    "type": "artist"
  },
  {
    "id": 10583405,
    "name": "Bad Bunny",
    "link": "https://www.deezer.com/artist/10583405",
    "picture": "https://api.deezer.com/artist/10583405/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/1000x1000-000000-80-0-0.jpg",
    "nb_album": 89,
    "nb_fan": 7728665,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/10583405/top?limit=50",
    "type": "artist"
  },
  {
    "id": 5297021,
    "name": "KAROL G",
    "link": "https://www.deezer.com/artist/5297021",
    "picture": "https://api.deezer.com/artist/5297021/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/1000x1000-000000-80-0-0.jpg",
    "nb_album": 74,
    "nb_fan": 3355592,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/5297021/top?limit=50",
    "type": "artist"
  },
  {
    "id": 12029862,
    "name": "Myke Towers",
    "link": "https://www.deezer.com/artist/12029862",
    "picture": "https://api.deezer.com/artist/12029862/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/1000x1000-000000-80-0-0.jpg",
    "nb_album": 177,
    "nb_fan": 1678056,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/12029862/top?limit=50",
    "type": "artist"
  },
  {
    "id": 6705223,
    "name": "Quevedo",
    "link": "https://www.deezer.com/artist/6705223",
    "picture": "https://api.deezer.com/artist/6705223/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/1000x1000-000000-80-0-0.jpg",
    "nb_album": 104,
    "nb_fan": 285982,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/6705223/top?limit=50",
    "type": "artist"
  },
  {
    "id": 11928391,
    "name": "Aitana",
    "link": "https://www.deezer.com/artist/11928391",
    "picture": "https://api.deezer.com/artist/11928391/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/1000x1000-000000-80-0-0.jpg",
    "nb_album": 58,
    "nb_fan": 343216,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/11928391/top?limit=50",
    "type": "artist"
  },
  {
    "id": 554792,
    "name": "ROSALÍA",
    "link": "https://www.deezer.com/artist/554792",
    "picture": "https://api.deezer.com/artist/554792/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/1000x1000-000000-80-0-0.jpg",
    "nb_album": 37,
    "nb_fan": 1020879,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/554792/top?limit=50",
    "type": "artist"
  },
  {
    "id": 111130212,
    "name": "Morad",
    "link": "https://www.deezer.com/artist/111130212",
    "picture": "https://api.deezer.com/artist/111130212/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/1000x1000-000000-80-0-0.jpg",
    "nb_album": 133,
    "nb_fan": 321531,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/111130212/top?limit=50",
    "type": "artist"
  },
  {
    "id": 2697,
    "name": "Melendi",
    "link": "https://www.deezer.com/artist/2697",
    "picture": "https://api.deezer.com/artist/2697/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/1000x1000-000000-80-0-0.jpg",
    "nb_album": 72,
    "nb_fan": 609011,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/2697/top?limit=50",
    "type": "artist"
  },
  {
    "id": 2792,
    "name": "Enrique Iglesias",
    "link": "https://www.deezer.com/artist/2792",
    "picture": "https://api.deezer.com/artist/2792/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/1000x1000-000000-80-0-0.jpg",
    "nb_album": 106,
    "nb_fan": 5940067,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/2792/top?limit=50",
    "type": "artist"
  },
  {
    "id": 70,
    "name": "Juanes",
    "link": "https://www.deezer.com/artist/70",
    "picture": "https://api.deezer.com/artist/70/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/1000x1000-000000-80-0-0.jpg",
    "nb_album": 114,
    "nb_fan": 1617792,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/70/top?limit=50",
    "type": "artist"
  },
  {
    "id": 4902904,
    "name": "DUKI",
    "link": "https://www.deezer.com/artist/4902904",
    "picture": "https://api.deezer.com/artist/4902904/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/1000x1000-000000-80-0-0.jpg",
    "nb_album": 155,
    "nb_fan": 817277,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/4902904/top?limit=50",
    "type": "artist"
  },
  {
    "id": 14343187,
    "name": "Maria Becerra",
    "link": "https://www.deezer.com/artist/14343187",
    "picture": "https://api.deezer.com/artist/14343187/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/1000x1000-000000-80-0-0.jpg",
    "nb_album": 75,
    "nb_fan": 375042,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/14343187/top?limit=50",
    "type": "artist"
  },
  {
    "id": 2252591,
    "name": "TINI",
    "link": "https://www.deezer.com/artist/2252591",
    "picture": "https://api.deezer.com/artist/2252591/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/1000x1000-000000-80-0-0.jpg",
    "nb_album": 79,
    "nb_fan": 904927,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/2252591/top?limit=50",
    "type": "artist"
  },
  {
    "id": 13299379,
    "name": "Nicki Nicole",
    "link": "https://www.deezer.com/artist/13299379",
    "picture": "https://api.deezer.com/artist/13299379/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/1000x1000-000000-80-0-0.jpg",
    "nb_album": 64,
    "nb_fan": 605429,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/13299379/top?limit=50",
    "type": "artist"
  },
  {
    "id": 12268072,
    "name": "Cazzu",
    "link": "https://www.deezer.com/artist/12268072",
    "picture": "https://api.deezer.com/artist/12268072/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/d4cb1c4b1f2524bbf40b0fa98c77e055/56x56-000000-80-0-0.jpg",

#### Listado de ID's

In [34]:
lista_id=[]
for d in artista_search:
    lista_id.append(d['id'])
print(lista_id)

[12246, 246791, 7188840, 525046, 4050205, 5531258, 71855892, 1194083, 9635624, 1562681, 10583405, 5297021, 12029862, 6705223, 11928391, 554792, 111130212, 2697, 2792, 70, 4902904, 14343187, 2252591, 13299379, 12268072, 5181388, 12637039, 160, 12487862, 61094422]

In [35]:
df=pd.DataFrame(artista_search)
df

,id,name,link,picture,picture_small,picture_medium,picture_big,picture_xl,nb_album,nb_fan,radio,tracklist,type
0,12246,Taylor Swift,https://www.deezer.com/artist/12246,https://api.deezer.com/artist/12246/image,https://cdn-images.dzcdn.net/images/artist/e52...,https://cdn-images.dzcdn.net/images/artist/e52...,https://cdn-images.dzcdn.net/images/artist/e52...,https://cdn-images.dzcdn.net/images/artist/e52...,124,12518191,True,https://api.deezer.com/artist/12246/top?limit=50,artist
1,246791,Drake,https://www.deezer.com/artist/246791,https://api.deezer.com/artist/246791/image,https://cdn-images.dzcdn.net/images/artist/5d2...,https://cdn-images.dzcdn.net/images/artist/5d2...,https://cdn-images.dzcdn.net/images/artist/5d2...,https://cdn-images.dzcdn.net/images/artist/5d2...,76,23929052,True,https://api.deezer.com/artist/246791/top?limit=50,artist
2,7188840,Morgan Wallen,https://www.deezer.com/artist/7188840,https://api.deezer.com/artist/7188840/image,https://cdn-images.dzcdn.net/images/artist/754...,https://cdn-images.dzcdn.net/images/artist/754...,https://cdn-images.dzcdn.net/images/artist/754...,https://cdn-images.dzcdn.net/images/artist/754...,41,281891,True,https://api.deezer.com/artist/7188840/top?limi...,artist
3,525046,Kendrick Lamar,https://www.deezer.com/artist/525046,https://api.deezer.com/artist/525046/image,https://cdn-images.dzcdn.net/images/artist/be0...,https://cdn-images.dzcdn.net/images/artist/be0...,https://cdn-images.dzcdn.net/images/artist/be0...,https://cdn-images.dzcdn.net/images/artist/be0...,40,6077190,True,https://api.deezer.com/artist/525046/top?limit=50,artist
4,4050205,The Weeknd,https://www.deezer.com/artist/4050205,https://api.deezer.com/artist/4050205/image,https://cdn-images.dzcdn.net/images/artist/581...,https://cdn-images.dzcdn.net/images/artist/581...,https://cdn-images.dzcdn.net/images/artist/581...,https://cdn-images.dzcdn.net/images/artist/581...,86,14418000,True,https://api.deezer.com/artist/4050205/top?limi...,artist
5,5531258,SZA,https://www.deezer.com/artist/5531258,https://api.deezer.com/artist/5531258/image,https://cdn-images.dzcdn.net/images/artist/8ce...,https://cdn-images.dzcdn.net/images/artist/8ce...,https://cdn-images.dzcdn.net/images/artist/8ce...,https://cdn-images.dzcdn.net/images/artist/8ce...,40,1282026,True,https://api.deezer.com/artist/5531258/top?limi...,artist
6,71855892,Zach Bryan,https://www.deezer.com/artist/71855892,https://api.deezer.com/artist/71855892/image,https://cdn-images.dzcdn.net/images/artist/552...,https://cdn-images.dzcdn.net/images/artist/552...,https://cdn-images.dzcdn.net/images/artist/552...,https://cdn-images.dzcdn.net/images/artist/552...,38,112288,True,https://api.deezer.com/artist/71855892/top?lim...,artist
7,1194083,"Tyler, The Creator",https://www.deezer.com/artist/1194083,https://api.deezer.com/artist/1194083/image,https://cdn-images.dzcdn.net/images/artist/5ec...,https://cdn-images.dzcdn.net/images/artist/5ec...,https://cdn-images.dzcdn.net/images/artist/5ec...,https://cdn-images.dzcdn.net/images/artist/5ec...,29,1322260,True,https://api.deezer.com/artist/1194083/top?limi...,artist
8,9635624,Billie Eilish,https://www.deezer.com/artist/9635624,https://api.deezer.com/artist/9635624/image,https://cdn-images.dzcdn.net/images/artist/8ea...,https://cdn-images.dzcdn.net/images/artist/8ea...,https://cdn-images.dzcdn.net/images/artist/8ea...,https://cdn-images.dzcdn.net/images/artist/8ea...,32,9108220,True,https://api.deezer.com/artist/9635624/top?limi...,artist
9,1562681,Ariana Grande,https://www.deezer.com/artist/1562681,https://api.deezer.com/artist/1562681/image,https://cdn-images.dzcdn.net/images/artist/5fc...,https://cdn-images.dzcdn.net/images/artist/5fc...,https://cdn-images.dzcdn.net/images/artist/5fc...,https://cdn-images.dzcdn.net/images/artist/5fc...,69,13297621,True,https://api.deezer.com/artist/1562681/top?limi...,artist
10,10583405,Bad Bunny,https://www.deezer.com/artist/10583405,https://api.deezer.com/artist/10583405/image,https://cdn-images.dzcdn.net/images/artist/45a...,https://cdn-images.dzcdn.net/images/artist/45a...,https://cdn-images.dzcdn.net/images/artist/45a...,https://cdn-images.dzcdn.net/images/artist/45a...,89,7728665,True,https://api.deezer.com/artist/10583405/top?lim...,artist
11,5297021,KAROL G,https://www.deezer.com/artist/5297021,https://api.deezer.com/artist/5297021/image,https://cdn-images.dzcdn.net/images/artist/dd8...,https://cdn-images.dzcdn.net/images/artist/dd8...,https://cdn-images.dzcdn.net/images/artist/dd8...,https://cdn-images.dzcdn.net/images/artist/dd8...,74,3355592,True,https://api.deezer.com/artist/5297021/top?limi...,artist
12,12029862,Myke Towers,https://www.deezer.com/artist/12029862,https://api.deezer.com/artist/12029862/image,https://cdn-images.dzcdn.net/images/artist/d3a...,https://cdn-images.dzcdn.net/images/artist/d3a...,https://cdn-images.dzcdn.net/images/artist/d3a...,https://cdn-images.dzcdn.net/images/artist/d3a...,177,1678056,True,https://api.deezer.com/artist/12029862/top?lim...,artist
13,6705223,Quevedo,https://www.deezer.com/artist/6705223,https://api.deezer.com/artist/6705223/image,https://cdn-images.dzcdn.net/images/artist/798...,https://cdn-images.dzcdn.net/images/artist/798...,https://cdn-images.dzcdn.net/images/artist/798...,https://cdn-images.dzcdn.net/images/artist/798...,104,285982,True,https://api.deezer.com/artist/6705223/top?limi...,artist
14,11928391,Aitana,https://www.deezer.com/artist/11928391,https://api.deezer.com/artist/11928391/image,https://cdn-images.dzcdn.net/images/artist/41a...,https://cdn-images.dzcdn.net/images/artist/41a...,https://cdn-images.dzcdn.net/images/artist/41a...,https://cdn-images.dzcdn.net/images/artist/41a...,58,343216,True,https://api.deezer.com/artist/11928391/top?lim...,artist
15,554792,ROSALÍA,https://www.deezer.com/artist/554792,https://api.deezer.com/artist/554792/image,https://cdn-images.dzcdn.net/images/artist/966...,https://cdn-images.dzcdn.net/images/artist/966...,https://cdn-images.dzcdn.net/images/artist/966...,https://cdn-images.dzcdn.net/images/artist/966...,37,1020879,True,https://api.deezer.com/artist/554792/top?limit=50,artist
16,111130212,Morad,https://www.deezer.com/artist/111130212,https://api.deezer.com/artist/111130212/image,https://cdn-images.dzcdn.net/images/artist/4c4...,https://cdn-images.dzcdn.net/images/artist/4c4...,https://cdn-images.dzcdn.net/images/artist/4c4...,https://cdn-images.dzcdn.net/images/artist/4c4...,133,321531,True,https://api.deezer.com/artist/111130212/top?li...,artist
17,2697,Melendi,https://www.deezer.com/artist/2697,https://api.deezer.com/artist/2697/image,https://cdn-images.dzcdn.net/images/artist/d06...,https://cdn-images.dzcdn.net/images/artist/d06...,https://cdn-images.dzcdn.net/images/artist/d06...,https://cdn-images.dzcdn.net/images/artist/d06...,72,609011,True,https://api.deezer.com/artist/2697/top?limit=50,artist
18,2792,Enrique Iglesias,https://www.deezer.com/artist/2792,https://api.deezer.com/artist/2792/image,https://cdn-images.dzcdn.net/images/artist/7c0...,https://cdn-images.dzcdn.net/images/artist/7c0...,https://cdn-images.dzcdn.net/images/artist/7c0...,https://cdn-images.dzcdn.net/images/artist/7c0...,106,5940067,True,https://api.deezer.com/artist/2792/top?limit=50,artist
19,70,Juanes,https://www.deezer.com/artist/70,https://api.deezer.com/artist/70/image,https://cdn-images.dzcdn.net/images/artist/bdc...,https://cdn-images.dzcdn.net/images/artist/bdc...,https://cdn-images.dzcdn.net/images/artist/bdc...,https://cdn-images.dzcdn.net/images/artist/bdc...,114,1617792,True,https://api.deezer.com/artist/70/top?limit=50,artist
20,4902904,DUKI,https://www.deezer.com/artist/4902904,https://api.deezer.com/artist/4902904/image,https://cdn-images.dzcdn.net/images/artist/795...,https://cdn-images.dzcdn.net/images/artist/795...,https://cdn-images.dzcdn.net/images/artist/795...,https://cdn-images.dzcdn.net/images/artist/795...,155,817277,True,https://api.deezer.com/artist/4902904/top?limi...,artist
21,14343187,Maria Becerra,https://www.deezer.com/artist/14343187,https://api.deezer.com/artist/14343187/image,https://cdn-images.dzcdn.net/images/artist/022...,https://cdn-images.dzcdn.net/images/artist/022...,https://cdn-images.dzcdn.net/images/artist/022...,https://cdn-images.dzcdn.net/images/artist/022...,75,375042,True,https://api.deezer.com/artist/14343187/top?lim...,artist
22,2252591,TINI,https://www.deezer.com/artist/2252591,https://api.deezer.com/artist/2252591/image,https://cdn-images.dzcdn.net/images/artist/efb...,https://cdn-images.dzcdn.net/images/artist/efb...,https://cdn-images.dzcdn.net/images/artist/efb...,https://cdn-images.dzcdn.net/images/artist/efb...,79,904927,True,https://api.deezer.com/artist/2252591/top?limi...,artist
23,13299379,Nicki Nicole,https://www.deezer.com/artist/13299379,https://api.deezer.com/artist/13299379/image,https://cdn-images.dzcdn.net/images/artist/7b4...,https://cdn-images.dzcdn.net/images/artist/7b4...,https://cdn-images.dzcdn.net/images/artist/7b4...,https://cdn-images.dzcdn.net/images/artist/7b4...,64,605429,True,https://api.deezer.com/artist/13299379/top?lim...,artist
24,12268072,Cazzu,https://www.deezer.com/artist/12268072,https://api.deezer.com/artist/12268072/image,https://cdn-images.dzcdn.net/images/artist/d4c...,https://cdn-images.dzcdn.net/images/artist/d4c...,https://cdn-images.dzcdn.net/images/artist/d4c...,https://cdn-images.dzcdn.net/images/artist/d4c...,56,598912,True,https://api.deezer.com/artist/12268072/top?lim...,artist
25,5181388,Lali,https://www.deezer.com/artist/5181388,https://api.deezer.com/artist/5181388/image,https://cdn-images.dzcdn.net/images/artist/bd8...,https://cdn-images.dzcdn.net/images/artist/bd8...,https://cdn-images.dzcdn.net/images/artist/bd8...,https://cdn-images.dzcdn.net/images/artist/bd8...,44,48334,True,https://api.deezer.com/artist/5181388/top?limi...,artist
26,12637039,Paulo Londra,https://www.deezer.com/artist/12637039,https://api.deezer.com/artist/12637039/image,https://cdn-images.dzcdn.net/images/artist/26f...,https://cdn-images.dzcdn.net/images/artist/26f...,https://cdn-images.dzcdn.net/images/artist/26f...,https://cdn-images.dzcdn.net/images/artist/26f...,48,1848168,True,https://api.deezer.com/artist/12637039/top?lim...,artist
27,160,Shakira,https://www.deezer.com/artist/160,https://api.deezer.com/artist/160/image,https://cdn-images.dzcdn.net/images/artist/69c...,https://cdn-images.dzcdn.net/images/artist/69c...,https://cdn-images.dzcdn.net/images/artist/69c...,https://cdn-images.dzcdn.net/images/artist/69c...,66,11471028,True,https://api.deezer.com/artist/160/top?limit=50,artist
28,12487862,Bizarrap,https://www.deezer.com/artist/12487862,https://api.deezer.com/artist/12487862/image,https://cdn-images.dzcdn.net/images/artist/e12...,https://cdn-images.dzcdn.net/images/artist/e12...,https://cdn-images.dzcdn.net/images/artist/e12...,https://cdn-images.dzcdn.net/images/artist/e12...,106,1112278,True,https://api.deezer.com/artist/12487862/top?lim...,artist
29,61094422,Emilia,https://www.deezer.com/artist/61094422,https://api.deezer.com/artist/61094422/image,https://cdn-images.dzcdn.net/images/artist/bd2...,https://cdn-images.dzcdn.net/images/artist/bd2...,https://cdn-images.dzcdn.net/images/artist/bd2...,https://cdn-images.dzcdn.net/images/artist/bd2...,50,105458,True,https://api.deezer.com/artist/61094422/top?lim...,artist

### Consulta de tracks (2 resultados incompletos Taylor S y TINI)

In [130]:
import requests
import time

def consulta_tracks(limit_por_artista, delay):
    lista_artistas = [
        "Taylor Swift", "Drake", "Morgan Wallen", "Kendrick Lamar", "The Weeknd",
        "SZA", "Zach Bryan", "Tyler the Creator", "Billie Eilish", "Ariana Grande",
        "Bad Bunny", "Karol G", "Myke Towers", "Quevedo", "Aitana",
        "Rosalía", "Morad", "Melendi", "Enrique Iglesias", "Juanes",
        "Duki", "María Becerra", "Tini Stoessel", "Nicki Nicole", "Cazzu",
        "Lali", "Paulo Londra", "Shakira", "Bizarrap", "Emilia",
    ]
    
    #headers para evitar bloqueos
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    
    tracks_search = {'id': [], 'title': [], 'rank': [], 'artist': []}
    
    for artista in lista_artistas:
        url= f"https://api.deezer.com/search/track?q=artist:\"{artista}\"&index=1&limit={limit_por_artista}"
        #url_1= f"https://api.deezer.com/search/track?q=artist:\"{artista}\"&limit={limit_por_artista}"
        print(f"Consultando tracks para: {artista}")
        
        try:
            respuesta = requests.get(url, headers=headers)
            if respuesta.status_code != 200:
                print(f"Error {respuesta.status_code} para {artista}")
                continue
            
            datos = respuesta.json()
            tracks = datos.get('data', [])
            
            if not tracks:              #en primer consulta arrojó 2 canciones para Taylor S.
                print(f"No se encontraron tracks para {artista}")
                continue
            
            for track in tracks:            #ver de agregar variables
                tracks_search['id'].append(track['id'])
                tracks_search['title'].append(track['title'])
                tracks_search['rank'].append(track.get('rank', 0))
                tracks_search['artist'].append(artista)  # guardamos el nombre buscado
            
            print(f"  → {len(tracks)} tracks obtenidos de {artista}")
            
        except Exception as e:
            print(f"Excepción con {artista}: {e}")
        
        # tiempo de espera para no sobrecargar la API
        time.sleep(delay)
    
    return tracks_search

# llamado y conversión a tabla
resultado = consulta_tracks(limit_por_artista=100, delay=1)
print(f"Total de tracks recolectados: {len(resultado['id'])}")

import pandas as pd
df = pd.DataFrame(resultado)
print(df.head())

Consultando tracks para: Taylor Swift
  → 1 tracks obtenidos de Taylor Swift
Consultando tracks para: Drake
  → 100 tracks obtenidos de Drake
Consultando tracks para: Morgan Wallen
  → 100 tracks obtenidos de Morgan Wallen
Consultando tracks para: Kendrick Lamar
  → 100 tracks obtenidos de Kendrick Lamar
Consultando tracks para: The Weeknd
  → 100 tracks obtenidos de The Weeknd
Consultando tracks para: SZA
  → 100 tracks obtenidos de SZA
Consultando tracks para: Zach Bryan
  → 100 tracks obtenidos de Zach Bryan
Consultando tracks para: Tyler the Creator
  → 100 tracks obtenidos de Tyler the Creator
Consultando tracks para: Billie Eilish
  → 86 tracks obtenidos de Billie Eilish
Consultando tracks para: Ariana Grande
  → 100 tracks obtenidos de Ariana Grande
Consultando tracks para: Bad Bunny
  → 100 tracks obtenidos de Bad Bunny
Consultando tracks para: Karol G
  → 100 tracks obtenidos de Karol G
Consultando tracks para: Myke Towers
  → 100 tracks obtenidos de Myke Towers
Consultando tracks para: Quevedo
  → 100 tracks obtenidos de Quevedo
Consultando tracks para: Aitana
  → 100 tracks obtenidos de Aitana
Consultando tracks para: Rosalía
  → 100 tracks obtenidos de Rosalía
Consultando tracks para: Morad
  → 100 tracks obtenidos de Morad
Consultando tracks para: Melendi
  → 100 tracks obtenidos de Melendi
Consultando tracks para: Enrique Iglesias
  → 100 tracks obtenidos de Enrique Iglesias
Consultando tracks para: Juanes
  → 100 tracks obtenidos de Juanes
Consultando tracks para: Duki
  → 100 tracks obtenidos de Duki
Consultando tracks para: María Becerra
  → 100 tracks obtenidos de María Becerra
Consultando tracks para: Tini Stoessel
  → 1 tracks obtenidos de Tini Stoessel
Consultando tracks para: Nicki Nicole
  → 100 tracks obtenidos de Nicki Nicole
Consultando tracks para: Cazzu
  → 100 tracks obtenidos de Cazzu
Consultando tracks para: Lali
  → 100 tracks obtenidos de Lali
Consultando tracks para: Paulo Londra
  → 80 tracks obtenidos de Paulo Londra
Consultando tracks para: Shakira
  → 100 tracks obtenidos de Shakira
Consultando tracks para: Bizarrap
  → 100 tracks obtenidos de Bizarrap
Consultando tracks para: Emilia
  → 100 tracks obtenidos de Emilia
Total de tracks recolectados: 2768
           id                            title    rank        artist
0  2617866132                            Sumer   25007  Taylor Swift
1  3398853341  Escape Artist (Remastered 2022)   49503         Drake
2   124603270                        One Dance  956192         Drake
3   474185072      Shake It Up (2017 Remaster)  529847         Drake
4  1463172782                Artisan Solitaire  236319         Drake

In [ ]:
#print(resultado)
print(json.dumps(resultado, indent=2, ensure_ascii=False)) #para ver estructura (diccionario con listas por cada columna)

{
  "id": [
    2595581052,
    2617866132,
    1440850322,
    3398853341,
    124603270,
    474185072,
    1463172782,
    1814108667,
    3945854591,
    3355430781,
    2490954011,
    144572210,
    1484144902,
    124603286,
    1024107692,
    533609232,
    608410332,
    118190298,
    1794149427,
    124603250,
    17347969,
    3232025631,
    1484144852,
    13529560,
    847699482,
    533609392,
    1024107672,
    74356181,
    17347964,
    3232025641,
    63565179,
    533609342,
    1050306812,
    1794149487,
    919708552,
    557240262,
    2973306121,
    2691966512,
    107878888,
    2972935451,
    6297750,
    453844292,
    144572214,
    623422582,
    1379123002,
    144572244,
    17347963,
    494383362,
    1794149437,
    144572216,
    124603278,
    947861152,
    79083410,
    144572212,
    144572248,
    70697364,
    17347979,
    5060528,
    642673932,
    2486117581,
    724098482,
    2486117521,
    596680492,
    947861092,
    2486117711,
    91543334,
    1484144872,
    124603258,
    144572218,
    2349399185,
    1733245187,
    3803503672,
    533609202,
    124603280,
    2912340531,
    7653922,
    947861082,
    1733245267,
    144572232,
    2864239792,
    500099532,
    75551473,
    2227136297,
    1484144822,
    95254404,
    578715552,
    17347967,
    947861122,
    95254428,
    95254422,
    124603254,
    2486117701,
    1999525067,
    3444551431,
    1794149367,
    1059242162,
    696957242,
    17347980,
    37027951,
    563085382,
    1470212372,
    2435239275,
    2780753191,
    1047020922,
    3366676861,
    3398208091,
    3398329531,
    3278152451,
    3206261161,
    862201652,
    2851395382,
    2851520332,
    3399879471,
    3399879601,
    3399879651,
    3399879451,
    2851520632,
    3366676251,
    2851520612,
    3399879631,
    3399879611,
    3399879511,
    3399879621,
    3471926691,
    3278158621,
    3399879641,
    3398329841,
    3398329671,
    3398329191,
    3398329381,
    1593324851,
    3398329761,
    3040572191,
    3399879681,
    2635850312,
    3399879591,
    3399879551,
    3366676941,
    3595357382,
    2851520622,
    3326163551,
    3398329121,
    3366676931,
    3399879661,
    3399879441,
    3399880091,
    2465963835,
    3366676281,
    3366676191,
    730818742,
    3399879581,
    3399879461,
    3399879671,
    2296711665,
    3161283401,
    3399879501,
    2867668712,
    3399879491,
    3366676471,
    3366676521,
    3792429142,
    3398329591,
    2851508002,
    3399879521,
    3398329851,
    3399879541,
    2851520732,
    3366676361,
    3366676531,
    3398329131,
    3398329351,
    3366676511,
    3366677031,
    3353801801,
    3366676321,
    3366676341,
    3366677111,
    3398329341,
    3398329201,
    2851395742,
    3398329601,
    3399879531,
    3366677071,
    3398329161,
    3398329801,
    3398329581,
    3398329791,
    3398329631,
    3398208171,
    3398329391,
    3398329641,
    3398329541,
    3398329411,
    3398329571,
    3398329471,
    3398329361,
    3398329301,
    1994973117,
    3398329371,
    3398329821,
    3398329261,
    3398329291,
    2783963122,
    3106586681,
    446082632,
    3152680431,
    511062642,
    3106586641,
    2715581062,
    67929157,
    1766771497,
    350171311,
    52735971,
    1766771587,
    97206068,
    3106586701,
    350171301,
    623422582,
    372049961,
    456011702,
    1476644212,
    350171251,
    1766771507,
    67929161,
    3855225991,
    1766771677,
    97206060,
    67929160,
    370426011,
    67929154,
    412241052,
    623422602,
    3106586621,
    350171331,
    350171271,
    3106586671,
    3106586631,
    75072823,
    723393482,
    67814846,
    136886992,
    97206080,
    1766771537,
    1766771517,
    1766771527,
    2783963112,
    67814849,
    669486712,
    74506420,
    723393442,
    3106586691,
    456965102,
    67814854,
    634438752,
    120380324,
    72089437,
    67929165,
    350171281,
    1766771557,
    2775438091,
    350171291,
    97206064,
    1766771627,
    67814844,
    95974638,
    67929162,
    560951892,
    67814847,
    1766771637,
    97206008,
    350171351,
    86401143,
    1766771667,
    85508154,
    350171321,
    17347970,
    2516448301,
    67929166,
    97206076,
    3058095781,
    67814855,
    3106586711,
    531856391,
    97206070,
    3106586731,
    2312477325,
    3106586661,
    3106586651,
    456965142,
    97206056,
    131391770,
    97206016,
    350171341,
    67814850,
    85508166,
    1766771647,
    120380320,
    3453936781,
    97206084,
    3596323222,
    460475962,
    1766771607,
    908604632,
    138603423,
    781460692,
    10235485,
    3139566641,
    3515929871,
    1685337397,
    908604612,
    1713175757,
    2338371075,
    1352360622,
    136889434,
    3210598411,
    106506512,
    3210598501,
    2321977215,
    2047662477,
    136889432,
    136889400,
    106506516,
    477452252,
    3210598391,
    908604622,
    92826786,
    3210598561,
    83844556,
    2747874731,
    2988053201,
    1614228192,
    1457107762,
    644296792,
    3210598441,
    62070468,
    3278625241,
    908604652,
    1225758662,
    79036873,
    1278960402,
    667570632,
    136889406,
    106506510,
    3210598591,
    122703266,
    456011702,
    1614226322,
    3210598381,
    1161752782,
    136889402,
    2164606877,
    383962071,
    908859832,
    2375967015,
    2747874801,
    2386586125,
    1614228242,
    62070464,
    3210598461,
    106506508,
    3210598481,
    1614228212,
    2166259397,
    1410738112,
    3210598511,
    106506526,
    908604582,
    136889414,
    3354177031,
    1278960492,
    2338371095,
    1506150362,
    1614226432,
    675343172,
    908859842,
    2247594637,
    1614226392,
    62070467,
    3210598431,
    1614226302,
    669486662,
    94664198,
    2747874881,
    477452262,
    3557222091,
    136889418,
    106506522,
    1103920482,
    3210598451,
    1543742002,
    136889410,
    106506514,
    396449622,
    3210598551,
    70106519,
    1787557067,
    1614226412,
    477452272,
    2715581022,
    70106530,
    98060376,
    477452292,
    789203172,
    71360922,
    12324459,
    1652871722,
    134124418,
    2161357,
    940981052,
    86143581,
    111959512,
    58904781,
    3246376311,
    2287577657,
    122719054,
    1709027947,
    3448193751,
    134124414,
    134124424,
    2791029492,
    134124432,
    134124430,
    134124440,
    134124416,
    134124412,
    2451110135,
    678135752,
    3263319,
    134124426,
    134124434,
    134124420,
    134124428,
    134124422,
    134124438,
    2159990047,
    1183073772,
    3273945191,
    1474495352,
    134124436,
    1481570,
    716744722,
    122411294,
    3371998941,
    3203045851,
    3565674011,
    1369066732,
    2613158982,
    3816548992,
    4832887,
    1481594,
    3055274551,
    480951472,
    3203045861,
    3218857851,
    3418861481,
    3944590221,
    677778612,
    3243007061,
    104096584,
    2742007531,
    2115913,
    111959860,
    3275539731,
    1481586,
    110955536,
    1769174057,
    58904971,
    1938147937,
    3279059491,
    411608542,
    122139868,
    17891655,
    117655880,
    3471736591,
    1481615,
    58904951,
    6914397,
    1481601,
    716521792,
    450146752,
    3464287301,
    699661202,
    1460679332,
    413294312,
    3448296421,
    10238657,
    519101112,
    13737581,
    3804291292,
    1514455,
    902491242,
    1394075782,
    64603051,
    1775628237,
    3476864111,
    2115907,
    600977272,
    2765590011,
    117056956,
    71354618,
    432946062,
    2176502,
    2814830342,
    3765755092,
    3761741952,
    3761742052,
    3761742092,
    2417266335,
    3761742022,
    1155415792,
    1152619842,
    1736518647,
    1714552247,
    3495656731,
    3761741962,
    3761742082,
    3440259571,
    2461839215,
    3761741972,
    3761742122,
    3512756601,
    3761742062,
    3761741982,
    3761741942,
    3761742072,
    1736518517,
    1816865977,
    3761742012,
    2067127917,
    1166835522,
    3761742002,
    1904534597,
    2067127687,
    3149745231,
    3765755172,
    1736518397,
    1736518407,
    1155415732,
    1736518357,
    2461839225,
    3421343401,
    3761742032,
    2417266375,
    1163301932,
    2417266355,
    3761741992,
    1166835512,
    1816865957,
    1166835492,
    1166835552,
    1155415722,
    1736518367,
    2118224167,
    3761742042,
    3765755212,
    1155415692,
    1152619832,
    2834425672,
    2461839235,
    1233891852,
    1155415682,
    1736518387,
    2417266195,
    3464052381,
    2417266295,
    1736518557,
    2417266345,
    3761742142,
    2067127727,
    1166835532,
    1816865967,
    1644968512,
    2417266255,
    3421343311,
    3761742112,
    3761742162,
    2417266275,
    3188835411,
    3421343391,
    1155415652,
    1166835562,
    1155415752,
    3765755152,
    3440259591,
    3080410171,
    3761742172,
    2067127707,
    2067127777,
    1736518347,
    1736518547,
    3421343461,
    1736518507,
    1736518437,
    3761742182,
    1736518527,
    3421343361,
    2417266175,
    1166835542,
    1736518417,
    1155415642,
    1166835502,
    1155415762,
    384157591,
    3470152941,
    3064010401,
    3453936791,
    681009752,
    446699712,
    3470153011,
    3064010361,
    681009652,
    559711712,
    1413669902,
    2215437737,
    3064010301,
    3470152951,
    859494212,
    3064010421,
    564320582,
    681009662,
    12292154,
    681009732,
    384157651,
    3064010411,
    3470152981,
    65723693,
    2245219087,
    384157601,
    1413669962,
    681009692,
    1391439912,
    384157571,
    1780549867,
    65723682,
    681009712,
    1413669892,
    102659150,
    1413669942,
    2215437777,
    1792992077,
    65723687,
    3470153001,
    578600182,
    1680292257,
    3064010391,
    14241662,
    3064010381,
    3064010351,
    3623651642,
    1413669922,
    3470153021,
    384157681,
    12292152,
    922331112,
    3064010291,
    14241668,
    12292151,
    1413670012,
    681009682,
    65723685,
    1413669952,
    2208390237,
    2215437587,
    3470152961,
    508003872,
    3777479862,
    98324154,
    3064010321,
    1614226362,
    16999969,
    717273782,
    681009702,
    585408102,
    65723681,
    578600192,
    3470152991,
    98324152,
    964845092,
    1413670002,
    3532148341,
    479629392,
    3470152971,
    135151150,
    972923202,
    689973242,
    384157641,
    71731844,
    384157631,
    1163783992,
    1413669982,
    12292161,
    1413669882,
    3470152931,
    384157621,
    3623651612,
    65723684,
    556225692,
    1413669972,
    98324144,
    681009742,
    12292163,
    65723677,
    2801558052,
    2366043655,
    2801558062,
    2801558042,
    2929354381,
    655095912,
    803010392,
    486928932,
    655095962,
    1449740592,
    2801558112,
    2801558032,
    655096022,
    877873612,
    2801558022,
    655095942,
    145343466,
    441178832,
    2801558102,
    2801558092,
    2801558082,
    2801558072,
    477338062,
    441178812,
    136337268,
    1216945442,
    655095992,
    1449740572,
    1833875727,
    142752898,
    711031072,
    2277080717,
    136246804,
    1449740502,
    1833875737,
    655095952,
    1449727402,
    1449740562,
    655095932,
    2813431572,
    441178822,
    1449740512,
    1483895182,
    1449727532,
    1140484252,
    1449727422,
    655096002,
    655095972,
    441178802,
    441178872,
    655095982,
    1449727382,
    1449740472,
    612132022,
    590067732,
    655096012,
    1449727432,
    441178882,
    1449727482,
    441178842,
    1449740452,
    655095922,
    1449740532,
    435906472,
    140119847,
    469407852,
    355738511,
    655096032,
    141340255,
    140119843,
    1449727462,
    141340253,
    140119845,
    141340251,
    1250420562,
    661235352,
    140119849,
    2289552565,
    141340257,
    655095902,
    3480266781,
    2441291635,
    1067793952,
    1166910502,
    1416790152,
    2296475575,
    717944342,
    1352360622,
    3294514251,
    2690050002,
    83844534,
    2614318122,
    629899842,
    542389552,
    81609384,
    1126047052,
    953769542,
    124995668,
    1375215222,
    1375215242,
    83844536,
    542389502,
    973317062,
    629899852,
    83844556,
    1375215262,
    83844544,
    2690049962,
    144130194,
    2690049982,
    3100316061,
    3294514131,
    724038592,
    2690049922,
    629899762,
    2981279421,
    1126047002,
    3294514261,
    131391768,
    629899822,
    541418452,
    2164606877,
    69959813,
    3294514281,
    1375215292,
    790914772,
    111052058,
    629899782,
    3294514291,
    3294514241,
    657493802,
    1375215332,
    3662731222,
    857206512,
    1249621332,
    83837268,
    3782340962,
    3294514271,
    1375215232,
    3100315991,
    629899862,
    69959806,
    3294514111,
    542373692,
    3100316011,
    542389542,
    69959816,
    2892932161,
    629899802,
    3100316021,
    2690049972,
    83844562,
    3294514121,
    1375215352,
    2690050022,
    133984340,
    3294514091,
    73248264,
    1375215272,
    1375215282,
    1287900732,
    3100315961,
    69959809,
    629899772,
    2690050012,
    1023602362,
    629899752,
    3045225161,
    135365006,
    1249621402,
    1375215212,
    1573552612,
    629899832,
    3662731132,
    1126047062,
    629899792,
    83837266,
    1126046952,
    1249621472,
    542389592,
    1126046962,
    69959815,
    1126047082,
    1126047022,
    790914822,
    1126046892,
    542389512,
    3171002981,
    3695893892,
    535391032,
    3171003131,
    3171003001,
    3171003091,
    3171003121,
    1741494317,
    1122450992,
    3171003021,
    3171003031,
    3171002991,
    3086954731,
    1741494417,
    1425937972,
    2496106371,
    3171003141,
    1741494307,
    3171003071,
    608410292,
    702421822,
    1741494477,
    1741494287,
    3171003111,
    3171003011,
    3171003061,
    2496106511,
    3171003081,
    972627922,
    3171003041,
    1155477802,
    704054322,
    889550982,
    686020062,
    3171003051,
    2496106541,
    3171003101,
    2316903805,
    1869675977,
    889550892,
    2289342455,
    1741494407,
    1412071172,
    1390823292,
    1741494447,
    1741494377,
    1498815252,
    1741494467,
    2042243747,
    2758436071,
    2496106431,
    1741494327,
    704078382,
    1045832172,
    2242449097,
    889550882,
    3457344911,
    1741494357,
    482413672,
    2473410281,
    608410332,
    1155477812,
    1741494457,
    2496106361,
    704078562,
    1741494347,
    2471293381,
    451149572,
    1741494487,
    2193354717,
    1741494437,
    1741494337,
    889550862,
    133297136,
    2496106391,
    776076902,
    1741494297,
    668529022,
    1155477892,
    1155477832,
    704059932,
    2496106381,
    482986842,
    1741494427,
    141553591,
    1741494387,
    875511852,
    702421812,
    411091822,
    1155477772,
    1451598462,
    889551002,
    3345061051,
    677305422,
    136305954,
    608410262,
    143986188,
    2496106451,
    482843042,
    1741494367,
    2846442802,
    2154046487,
    3421452631,
    796342592,
    1721634237,
    2154046577,
    3421452581,
    3421452651,
    2154046437,
    714210042,
    3376766301,
    3421452481,
    3421452551,
    2403815945,
    1649460922,
    1283546482,
    2154046457,
    1049272552,
    1496293332,
    3421452521,
    3421452471,
    2404468105,
    2403815955,
    2403815915,
    2154046537,
    1583346082,
    2356322575,
    3353740701,
    2655316752,
    3076608311,
    518459732,
    2403816025,
    1283546522,
    2154046597,
    2006806507,
    3421452541,
    2131900117,
    3421452601,
    553957272,
    1882539797,
    575891702,
    2403816065,
    616539122,
    3421452501,
    1110762302,
    3421452531,
    2403816105,
    1444099622,
    1283546502,
    477392342,
    365643061,
    3667253872,
    2301174945,
    3421452511,
    497151272,
    2381438915,
    2154046507,
    2547799552,
    3421452621,
    2154046497,
    2154046517,
    961348062,
    2154046557,
    3421452611,
    672202162,
    2570906182,
    1233167142,
    1012504022,
    625967372,
    2959868521,
    2005370277,
    130908258,
    2154046477,
    1150505002,
    2154046467,
    3421452591,
    3421452561,
    3031011641,
    1407492942,
    1567098932,
    648273462,
    1283546542,
    657761942,
    1283546492,
    525996902,
    671255752,
    2403815975,
    1283546622,
    2154046567,
    121124374,
    623698202,
    2403815905,
    465649852,
    672202212,
    672202232,
    3421452461,
    420227712,
    3421452571,
    1799244447,
    917384132,
    3852034961,
    3368936011,
    1095137892,
    2045122487,
    978387002,
    2542594331,
    2159990627,
    2758436071,
    2294944375,
    2927624581,
    3824901081,
    3039942561,
    857827262,
    1049272552,
    2309824565,
    2542594411,
    1496278042,
    1331984152,
    3147491001,
    937416142,
    857827162,
    1142380132,
    3913631501,
    3380325261,
    1440185042,
    2321212095,
    3260565211,
    1044802062,
    857827242,
    3952366141,
    857827272,
    1172384912,
    857827192,
    974000002,
    828486762,
    1399887862,
    717285742,
    537872822,
    751158212,
    3069012151,
    1677750597,
    2348872955,
    773615482,
    857827172,
    705425882,
    566770762,
    662274202,
    2159990517,
    2193354727,
    909576642,
    2159990507,
    3202603181,
    696690342,
    3279575191,
    1139120212,
    3697524132,
    3429928271,
    2912364201,
    2714132532,
    1172384892,
    744909942,
    717740522,
    3630404192,
    1262234002,
    1078759092,
    909336752,
    2159990637,
    857827232,
    568685952,
    1815768717,
    1162056102,
    857827212,
    3945244821,
    1053377172,
    1226448792,
    2804986202,
    1193945962,
    857827152,
    691388272,
    1386230782,
    1538953552,
    1567099042,
    665914662,
    2159990497,
    2423937665,
    1044802612,
    2159990417,
    1351104232,
    3202603251,
    857827322,
    2473410251,
    2159990617,
    705581612,
    2927624541,
    1324636742,
    1674916197,
    2159990537,
    1952987777,
    2067040937,
    889551012,
    2182785557,
    72993990,
    3843020331,
    1426036652,
    3911872941,
    3382134521,
    1811481707,
    3368936011,
    3274807471,
    3104740761,
    3447342231,
    2045122487,
    3217533771,
    3104740891,
    3104740681,
    3217411961,
    2154046457,
    3104740881,
    3217411241,
    3104740951,
    3480440021,
    3219256631,
    3668430692,
    3217407501,
    3217535331,
    2248629077,
    2482830851,
    2313435675,
    3358977371,
    3217412491,
    3217535281,
    1981818727,
    3217535351,
    2233549207,
    3104740921,
    3655199202,
    2462969875,
    2195211937,
    3104740971,
    1599437392,
    3217535451,
    3217535291,
    3104740791,
    2545940182,
    2552447642,
    3219524511,
    3065851061,
    3296726521,
    3217535391,
    3104740731,
    2010116887,
    2035201357,
    3219260371,
    3217535381,
    2021305867,
    3104740871,
    1700761967,
    3217535341,
    2294688245,
    2494111761,
    3217535371,
    2294428925,
    3104740811,
    3217532481,
    3104740941,
    3217535411,
    3104740841,
    2338469455,
    3104740931,
    1522054342,
    3217533601,
    1640690782,
    2544359381,
    3104740961,
    3682563722,
    2288414387,
    3217535421,
    3104740901,
    1775141327,
    3219265341,
    3104740911,
    3219258361,
    3219524601,
    3028526781,
    3217535691,
    3217535401,
    3219524531,
    3219263651,
    3093701881,
    3219267021,
    3217534951,
    3141215631,
    2528094481,
    3332869311,
    3219524481,
    2498512571,
    2459120415,

In [13]:
df=pd.DataFrame(resultado)
df

,id,title,rank,artist
0,2595581052,kilómetros De Amor,22388,Taylor Swift
1,2617866132,Sumer,25007,Taylor Swift
2,1440850322,Les artistes,85620,Drake
3,3398853341,Escape Artist (Remastered 2022),49503,Drake
4,124603270,One Dance,956192,Drake
...,...,...,...,...
2767,1100416592,Bendición,190576,Emilia
2768,864971502,Big Big World (Pierre J's Big Radio Remix),309656,Emilia
2769,3606479902,Maldita Noche En Vivo,200178,Emilia
2770,885079502,No Más,204914,Emilia
2771,3608292922,BOTA,416481,Emilia

#### Consulta modelo de tracks (Taylor Swift y Tini Stoessel - 100 canciones)

In [38]:
import re

def llamar():
    #url='https://api.deezer.com/search/track?q=taylor&swift=undefined&index=0&limit=100'    """FUNCION OK PARA TAYLOR"""
    url00="https://api.deezer.com/search/track?q=TINI&index=0&limit=100" #"id": "2252591","name": "TINI",
    headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }


    respuesta = requests.get(url00,headers=headers)
    if respuesta.status_code != 200:
        print(f"Error: {respuesta.status_code}")
    else:
        datos = respuesta.json()
        tracks = datos.get('data',[])
        return tracks

In [40]:
consulta_tini=llamar()
#print(json.dumps(a,indent=2,ensure_ascii=False))

In [41]:
len(consulta_tini)

93

In [43]:
print(json.dumps(consulta_tini,indent=2,ensure_ascii=False))

[
  {
    "id": 2498029491,
    "readable": true,
    "title": "La_Original.mp3",
    "title_short": "La_Original.mp3",
    "title_version": "",
    "isrc": "USSD12300584",
    "link": "https://www.deezer.com/track/2498029491",
    "duration": 140,
    "rank": 541606,
    "explicit_lyrics": false,
    "explicit_content_lyrics": 0,
    "explicit_content_cover": 2,
    "preview": "https://cdnt-preview.dzcdn.net/api/1/1/9/5/4/0/9543ac2cd39b5d63effa25c9328d8b4e.mp3?hdnea=exp=1777035673~acl=/api/1/1/9/5/4/0/9543ac2cd39b5d63effa25c9328d8b4e.mp3*~data=user_id=0,application_id=42~hmac=03dfdbbe47ea5b8f90a7371038d766c6ea16cdd8f4a5408823663bf60e2e246e",
    "md5_image": "1eb3b9ecd27cd1be09d01cc8ff513ecb",
    "artist": {
      "id": 61094422,
      "name": "Emilia",
      "link": "https://www.deezer.com/artist/61094422",
      "picture": "https://api.deezer.com/artist/61094422/image",
      "picture_small": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/56x56-000000-80-0-0.jpg",
      "picture_medium": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/250x250-000000-80-0-0.jpg",
      "picture_big": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/500x500-000000-80-0-0.jpg",
      "picture_xl": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/1000x1000-000000-80-0-0.jpg",
      "tracklist": "https://api.deezer.com/artist/61094422/top?limit=50",
      "type": "artist"
    },
    "album": {
      "id": 499990281,
      "title": "La_Original.mp3",
      "cover": "https://api.deezer.com/album/499990281/image",
      "cover_small": "https://cdn-images.dzcdn.net/images/cover/1eb3b9ecd27cd1be09d01cc8ff513ecb/56x56-000000-80-0-0.jpg",
      "cover_medium": "https://cdn-images.dzcdn.net/images/cover/1eb3b9ecd27cd1be09d01cc8ff513ecb/250x250-000000-80-0-0.jpg",
      "cover_big": "https://cdn-images.dzcdn.net/images/cover/1eb3b9ecd27cd1be09d01cc8ff513ecb/500x500-000000-80-0-0.jpg",
      "cover_xl": "https://cdn-images.dzcdn.net/images/cover/1eb3b9ecd27cd1be09d01cc8ff513ecb/1000x1000-000000-80-0-0.jpg",
      "md5_image": "1eb3b9ecd27cd1be09d01cc8ff513ecb",
      "tracklist": "https://api.deezer.com/album/499990281/tracks",
      "type": "album"
    },
    "type": "track"
  },
  {
    "id": 3288087861,
    "readable": true,
    "title": "blackout ?",
    "title_short": "blackout ?",
    "title_version": "",
    "isrc": "USSD12500117",
    "link": "https://www.deezer.com/track/3288087861",
    "duration": 180,
    "rank": 577836,
    "explicit_lyrics": false,
    "explicit_content_lyrics": 0,
    "explicit_content_cover": 2,
    "preview": "https://cdnt-preview.dzcdn.net/api/1/1/4/9/3/0/49390d5f9b4a2ab72f844858653c663e.mp3?hdnea=exp=1777035673~acl=/api/1/1/4/9/3/0/49390d5f9b4a2ab72f844858653c663e.mp3*~data=user_id=0,application_id=42~hmac=a8d1407e3220c1cf5a404e460e043c2b2afbde52f600a7c1362d8746e467fbb8",
    "md5_image": "fee888110d29c7d8021275c36004961f",
    "artist": {
      "id": 61094422,
      "name": "Emilia",
      "link": "https://www.deezer.com/artist/61094422",
      "picture": "https://api.deezer.com/artist/61094422/image",
      "picture_small": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/56x56-000000-80-0-0.jpg",
      "picture_medium": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/250x250-000000-80-0-0.jpg",
      "picture_big": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/500x500-000000-80-0-0.jpg",
      "picture_xl": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/1000x1000-000000-80-0-0.jpg",
      "tracklist": "https://api.deezer.com/artist/61094422/top?limit=50",
      "type": "artist"
    },
    "album": {
      "id": 730638231,
      "title": "blackout ?",
      "cover": "https://api.deezer.com/album/730638231/image",
      "cover_small": "https://cdn-images.dzcdn.net/images/cover/fee888110d29c7d8021275c36004961f/56x56-000000-80-0-0.jpg",
      "cover_medium": "https://cdn-images.dzcdn.net/images/cover/fee888110d29c7d8021275c36004961f/250x250-000000-80-0-0.jpg",
      "cover_big": "https://cdn-images.dzcdn.net/images/cover/fee888110d29c7d8021275c36004961f/500x500-000000-80-0-0.jpg",
      "cover_xl": "https://cdn-images.dzcdn.net/images/cover/fee888110d29c7d8021275c36004961f/1000x1000-000000-80-0-0.jpg",
      "md5_image": "fee888110d29c7d8021275c36004961f",
      "tracklist": "https://api.deezer.com/album/730638231/tracks",
      "type": "album"
    },
    "type": "track"
  },
  {
    "id": 1415274362,
    "readable": true,
    "title": "La Niña de la Escuela",
    "title_short": "La Niña de la Escuela",
    "title_version": "",
    "isrc": "ES5702100732",
    "link": "https://www.deezer.com/track/1415274362",
    "duration": 204,
    "rank": 567777,
    "explicit_lyrics": false,
    "explicit_content_lyrics": 0,
    "explicit_content_cover": 0,
    "preview": "https://cdnt-preview.dzcdn.net/api/1/1/9/4/2/0/942ee634f0f24e6102abaef37bf0634e.mp3?hdnea=exp=1777035673~acl=/api/1/1/9/4/2/0/942ee634f0f24e6102abaef37bf0634e.mp3*~data=user_id=0,application_id=42~hmac=18977c4f40276f05d392ab4c1d9a2bd580f39ae38575b00dcf1eaf312321cdaa",
    "md5_image": "9a727073b88de02008749d70d54d029c",
    "artist": {
      "id": 48765861,
      "name": "Lola Indigo",
      "link": "https://www.deezer.com/artist/48765861",
      "picture": "https://api.deezer.com/artist/48765861/image",
      "picture_small": "https://cdn-images.dzcdn.net/images/artist/f87b9bce8f420d9a2116680be75e7878/56x56-000000-80-0-0.jpg",
      "picture_medium": "https://cdn-images.dzcdn.net/images/artist/f87b9bce8f420d9a2116680be75e7878/250x250-000000-80-0-0.jpg",
      "picture_big": "https://cdn-images.dzcdn.net/images/artist/f87b9bce8f420d9a2116680be75e7878/500x500-000000-80-0-0.jpg",
      "picture_xl": "https://cdn-images.dzcdn.net/images/artist/f87b9bce8f420d9a2116680be75e7878/1000x1000-000000-80-0-0.jpg",
      "tracklist": "https://api.deezer.com/artist/48765861/top?limit=50",
      "type": "artist"
    },
    "album": {
      "id": 239883572,
      "title": "La Niña",
      "cover": "https://api.deezer.com/album/239883572/image",
      "cover_small": "https://cdn-images.dzcdn.net/images/cover/9a727073b88de02008749d70d54d029c/56x56-000000-80-0-0.jpg",
      "cover_medium": "https://cdn-images.dzcdn.net/images/cover/9a727073b88de02008749d70d54d029c/250x250-000000-80-0-0.jpg",
      "cover_big": "https://cdn-images.dzcdn.net/images/cover/9a727073b88de02008749d70d54d029c/500x500-000000-80-0-0.jpg",
      "cover_xl": "https://cdn-images.dzcdn.net/images/cover/9a727073b88de02008749d70d54d029c/1000x1000-000000-80-0-0.jpg",
      "md5_image": "9a727073b88de02008749d70d54d029c",
      "tracklist": "https://api.deezer.com/album/239883572/tracks",
      "type": "album"
    },
    "type": "track"
  },
  {
    "id": 3907274501,
    "readable": true,
    "title": "Dos Amantes",
    "title_short": "Dos Amantes",
    "title_version": "",
    "isrc": "USHR12652960",
    "link": "https://www.deezer.com/track/3907274501",
    "duration": 188,
    "rank": 598977,
    "explicit_lyrics": false,
    "explicit_content_lyrics": 0,
    "explicit_content_cover": 2,
    "preview": "https://cdnt-preview.dzcdn.net/api/1/1/a/e/8/0/ae8f6924dbf0de0fffc639448eab7b41.mp3?hdnea=exp=1777035673~acl=/api/1/1/a/e/8/0/ae8f6924dbf0de0fffc639448eab7b41.mp3*~data=user_id=0,application_id=42~hmac=f4ce354952b2d1699b317d1781f746d9dd07ed174c84a74cf227c178bd125c3d",
    "md5_image": "d61b81fa3d9e3b40fabb91cb14ba30cc",
    "artist": {
      "id": 2252591,
      "name": "TINI",
      "link": "https://www.deezer.com/artist/2252591",
      "picture": "https://api.deezer.com/artist/2252591/image",
      "picture_small": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/56x56-000000-80-0-0.jpg",
      "picture_medium": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/250x250-000000-80-0-0.jpg",
      "picture_big": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/500x500-000000-80-0-0.jpg",
      "picture_xl": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/1000x1000-000000-80-0-0.jpg",
      "tracklist": "https://api.deezer.com/artist/2252591/top?limit=50",
      "type": "artist"
    },
    "album": {
      "id": 942083251,
      "title": "Dos Amantes",
      "cover": "https://api.deezer.com/album/942083251/image",
      "cover_small": "https://cdn-images.dzcdn.net/images/cover/d61b81fa3d9e3b40fabb91cb14ba30cc/56x56-000000-80-0-0.jpg",
      "cover_medium": "https://cdn-images.dzcdn.net/images/cover/d61b81fa3d9e3b40fabb91cb14ba30cc/250x250-000000-80-0-0.jpg",
      "cover_big": "https://cdn-images.dzcdn.net/images/cover/d61b81fa3d9e3b40fabb91cb14ba30cc/500x500-000000-80-0-0.jpg",
      "cover_xl": "https://cdn-images.dzcdn.net/images/cover/d61b81fa3d9e3b40fabb91cb14ba30cc/1000x1000-000000-80-0-0.jpg",
      "md5_image": "d61b81fa3d9e3b40fabb91cb14ba30cc",
      "tracklist": "https://api.deezer.com/album/942083251/tracks",
      "type": "album"
    },
    "type": "track"
  },
  {
    "id": 1349596782,
    "readable": true,
    "title": "Miénteme",
    "title_short": "Miénteme",
    "title_version": "",
    "isrc": "USHR12141512",
    "link": "https://www.deezer.com/track/1349596782",
    "duration": 165,
    "rank": 640928,
    "explicit_lyrics": false,
    "explicit_content_lyrics": 0,
    "explicit_content_cover": 2,
    "preview": "https://cdnt-preview.dzcdn.net/api/1/1/b/7/0/0/b7043937515638675a3ac002a49f9641.mp3?hdnea=exp=1777035673~acl=/api/1/1/b/7/0/0/b7043937515638675a3ac002a49f9641.mp3*~data=user_id=0,application_id=42~hmac=1e8d394df416c3fbb16818356c845843c40516c6ace01a45cd2dcda7a7483203",
    "md5_image": "3e6361aae5a06412f6029a371ddb464f",
    "artist": {
      "id": 2252591,
      "name": "TINI",
      "link": "https://www.deezer.com/artist/2252591",
      "picture": "https://api.deezer.com/artist/2252591/image",
      "picture_small": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/56x56-000000-80-0-0.jpg",
      "picture_medium": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/250x250-000000-80-0-0.jpg",
      "picture_big": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/500x500-000000-80-0-0.jpg",
      "picture_xl": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/1000x1000-000000-80-0-0.jpg",
      "tracklist": "https://api.deezer.com/artist/2252591/top?limit=50",
      "type": "artist"
    },
    "album": {
      "id": 224353382,
      "title": "Miénteme",
      "cover": "https://api.deezer.com/album/224353382/image",
      "cover_small": "https://cdn-images.dzcdn.net/images/cover/3e6361aae5a06412f6029a371ddb464f/56x56-000000-80-0-0.jpg",
      "cover_medium": "https://cdn-images.dzcdn.net/images/cover/3e6361aae5a06412f6029a371ddb464f/250x250-000000-80-0-0.jpg",
      "cover_big": "https://cdn-images.dzcdn.net/images/cover/3e6361aae5a06412f6029a371ddb464f/500x500-000000-80-0-0.jpg",
      "cover_xl": "https://cdn-images.dzcdn.net/images/cover/3e6361aae5a06412f6029a371ddb464f/1000x1000-000000-80-0-0.jpg",
      "md5_image": "3e6361aae5a06412f6029a371ddb464f",
      "tracklist": "https://api.deezer.com/album/224353382/tracks",
      "type": "album"
    },
    "type": "track"
  },
  {
    "id": 1451177572,
    "readable": true,
    "title": "Maldita Foto",
    "title_short": "Maldita Foto",
    "title_version": "",
    "isrc": "USHR12141956",
    "link": "https://www.deezer.com/track/1451177572",
    "duration": 190,
    "rank": 430039,
    "explicit_lyrics": false,
    "explicit_content_lyrics": 0,
    "explicit_content_cover": 2,
    "preview": "https://cdnt-preview.dzcdn.net/api/1/1/b/7/9/0/b79315b9def295219c324843179d5b64.mp3?hdnea=exp=1777035673~acl=/api/1/1/b/7/9/0/b79315b9def295219c324843179d5b64.mp3*~data=user_id=0,application_id=42~hmac=069fe65d218920151735cc8b524c23bc729db1daaf4e4bf5ce57ceb4f2de0da4",
    "md5_image": "f54d05fc2c9c0880b754f9d1e8b4236b",
    "artist": {
      "id": 2252591,
      "name": "TINI",
      "link": "https://www.deezer.com/artist/2252591",
      "picture": "https://api.deezer.com/artist/2252591/image",
      "picture_small": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/56x56-000000-80-0-0.jpg",
      "picture_medium": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/250x250-000000-80-0-0.jpg",
      "picture_big": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/500x500-000000-80-0-0.jpg",
      "picture_xl": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/1000x1000-000000-80-0-0.jpg",
      "tracklist": "https://api.deezer.com/artist/2252591/top?limit=50",
      "type": "artist"
    },
    "album": {
      "id": 248560362,
      "title": "Maldita Foto",
      "cover": "https://api.deezer.com/album/248560362/image",
      "cover_small": "https://cdn-images.dzcdn.net/images/cover/f54d05fc2c9c0880b754f9d1e8b4236b/56x56-000000-80-0-0.jpg",
      "cover_medium": "https://cdn-images.dzcdn.net/images/cover/f54d05fc2c9c0880b754f9d1e8b4236b/250x250-000000-80-0-0.jpg",
      "cover_big": "https://cdn-images.dzcdn.net/images/cover/f54d05fc2c9c0880b754f9d1e8b4236b/500x500-000000-80-0-0.jpg",
      "cover_xl": "https://cdn-images.dzcdn.net/images/cover/f54d05fc2c9c0880b754f9d1e8b4236b/1000x1000-000000-80-0-0.jpg",
      "md5_image": "f54d05fc2c9c0880b754f9d1e8b4236b",
      "tracklist": "https://api.deezer.com/album/248560362/tracks",
      "type": "album"
    },
    "type": "track"
  },
  {
    "id": 3403101261,
    "readable": true,
    "title": "Universidad",
    "title_short": "Universidad",
    "title_version": "",
    "isrc": "USHR12550967",
    "link": "https://www.deezer.com/track/3403101261",
    "duration": 158,
    "rank": 593349,
    "explicit_lyrics": false,
    "explicit_content_lyrics": 0,
    "explicit_content_cover": 2,
    "preview": "https://cdnt-preview.dzcdn.net/api/1/1/f/7/9/0/f796d7498e00a1f13d3e595454a106a4.mp3?hdnea=exp=1777035673~acl=/api/1/1/f/7/9/0/f796d7498e00a1f13d3e595454a106a4.mp3*~data=user_id=0,application_id=42~hmac=47827866f6a700141e904b663745f4ff47cb800fb0b8bc009921ffc0e7cf5cba",
    "md5_image": "2521629f12d9e8e85cef8b65f284bbd4",
    "artist": {
      "id": 2252591,
      "name": "TINI",
      "link": "https://www.deezer.com/artist/2252591",
      "picture": "https://api.deezer.com/artist/2252591/image",
      "picture_small": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/56x56-000000-80-0-0.jpg",
      "picture_medium": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/250x250-000000-80-0-0.jpg",
      "picture_big": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/500x500-000000-80-0-0.jpg",
      "picture_xl": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/1000x1000-000000-80-0-0.jpg",
      "tracklist": "https://api.deezer.com/artist/2252591/top?limit=50",
      "type": "artist"
    },
    "album": {
      "id": 768688871,
      "title": "Universidad",
      "cover": "https://api.deezer.com/album/768688871/image",
      "cover_small": "https://cdn-images.dzcdn.net/images/cover/2521629f12d9e8e85cef8b65f284bbd4/56x56-000000-80-0-0.jpg",
      "cover_medium": "https://cdn-images.dzcdn.net/images/cover/2521629f12d9e8e85cef8b65f284bbd4/250x250-000000-80-0-0.jpg",
      "cover_big": "https://cdn-images.dzcdn.net/images/cover/2521629f12d9e8e85cef8b65f284bbd4/500x500-000000-80-0-0.jpg",
      "cover_xl": "https://cdn-images.dzcdn.net/images/cover/2521629f12d9e8e85cef8b65f284bbd4/1000x1000-000000-80-0-0.jpg",
      "md5_image": "2521629f12d9e8e85cef8b65f284bbd4",
      "tracklist": "https://api.deezer.com/album/768688871/tracks",
      "type": "album"
    },
    "type": "track"
  },
  {
    "id": 3103119731,
    "readable": true,
    "title": "el cielo",
    "title_short": "el cielo",
    "title_version": "",
    "isrc": "USHR12449118",
    "link": "https://www.deezer.com/track/3103119731",
    "duration": 188,
    "rank": 553765,
    "explicit_lyrics": false,
    "explicit_content_lyrics": 0,
    "explicit_content_cover": 2,
    "preview": "https://cdnt-preview.dzcdn.net/api/1/1/4/2/3/0/423935fe0095b02c764f8eaf08252fc0.mp3?hdnea=exp=1777035673~acl=/api/1/1/4/2/3/0/423935fe0095b02c764f8eaf08252fc0.mp3*~data=user_id=0,application_id=42~hmac=23fc169601ad8019d3015750bb0dc294380416fabb2fbefcaec8249e65e94077",
    "md5_image": "08d98bec253fba3caedafcad7cdce62f",
    "artist": {
      "id": 2252591,
      "name": "TINI",
      "link": "https://www.deezer.com/artist/2252591",
      "picture": "https://api.deezer.com/artist/2252591/image",
      "picture_small": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/56x56-000000-80-0-0.jpg",
      "picture_medium": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/250x250-000000-80-0-0.jpg",
      "picture_big": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/500x500-000000-80-0-0.jpg",
      "picture_xl": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/1000x1000-000000-80-0-0.jpg",
      "tracklist": "https://api.deezer.com/artist/2252591/top?limit=50",
      "type": "artist"
    },
    "album": {
      "id": 673075801,
      "title": "el cielo",
      "cover": "https://api.deezer.com/album/673075801/image",
      "cover_small": "https://cdn-images.dzcdn.net/images/cover/08d98bec253fba3caedafcad7cdce62f/56x56-000000-80-0-0.jpg",
      "cover_medium": "https://cdn-images.dzcdn.net/images/cover/08d98bec253fba3caedafcad7cdce62f/250x250-000000-80-0-0.jpg",
      "cover_big": "https://cdn-images.dzcdn.net/images/cover/08d98bec253fba3caedafcad7cdce62f/500x500-000000-80-0-0.jpg",
      "cover_xl": "https://cdn-images.dzcdn.net/images/cover/08d98bec253fba3caedafcad7cdce62f/1000x1000-000000-80-0-0.jpg",
      "md5_image": "08d98bec253fba3caedafcad7cdce62f",
      "tracklist": "https://api.deezer.com/album/673075801/tracks",
      "type": "album"
    },
    "type": "track"
  },
  {
    "id": 3546865111,
    "readable": true,
    "title": "HASTA QUE ME ENAMORO",
    "title_short": "HASTA QUE ME ENAMORO",
    "title_version": "",
    "isrc": "USWL12504691",
    "link": "https://www.deezer.com/track/3546865111",
    "duration": 180,
    "rank": 549787,
    "explicit_lyrics": false,
    "explicit_content_lyrics": 0,
    "explicit_content_cover": 2,
    "preview": "https://cdnt-preview.dzcdn.net/api/1/1/c/c/8/0/cc8efff0c0ebdc0c3f2b8aa8b3f433cc.mp3?hdnea=exp=1777035673~acl=/api/1/1/c/c/8/0/cc8efff0c0ebdc0c3f2b8aa8b3f433cc.mp3*~data=user_id=0,application_id=42~hmac=a243fc6088ce7358ea3748bb039e7eef7e22a70e7300ba76dda071196acf7b5e",
    "md5_image": "83386249716cb44d28d5906334951124",
    "artist": {
      "id": 14343187,
      "name": "Maria Becerra",
      "link": "https://www.deezer.com/artist/14343187",
      "picture": "https://api.deezer.com/artist/14343187/image",
      "picture_small": "https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/56x56-000000-80-0-0.jpg",
      "picture_medium": "https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/250x250-000000-80-0-0.jpg",
      "picture_big": "https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/500x500-000000-80-0-0.jpg",
      "picture_xl": "https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/1000x1000-000000-80-0-0.jpg",
      "tracklist": "https://api.deezer.com/artist/14343187/top?limit=50",
      "type": "artist"
    },
    "album": {
      "id": 818230011,
      "title": "HASTA QUE ME ENAMORO",
      "cover": "https://api.deezer.com/album/818230011/image",

##### Función para limpiar tracks

In [58]:
def depurar():  
    lista_tini_depurada=[]
    for track in consulta_tini:
        if "TINI" not in track['artist']['name']:
            continue
        else:
            lista_tini_depurada.append(track)
            
    print(f"Se encontraron {len(lista_tini_depurada)} resultados.")
            
    
    return lista_tini_depurada
TINI=depurar()

Se encontraron 71 resultados.

In [ ]:
for r in TINI:
    print(f" - {r['title']}")

#SE OBSERVAN RESULTADOS DUPLICADOS

 - Dos Amantes
 - Miénteme
 - Maldita Foto
 - Universidad
 - el cielo
 - El Cielo + Fresa LIVE
 - Una Noche Más
 - La Loto
 - Carne y Hueso
 - Fantasi
 - Te Pido Live
 - Consejo de Amor (feat. Morat)
 - Bar
 - Las Jordans
 - Cupido
 - Muñecas
 - Fresa
 - La Triple T
 - 36 Vidas
 - Oye
 - Suéltate el Pelo
 - Cupido LIVE
 - me voy en vivo
 - Un Beso en Madrid
 - pa
 - Siempre Brillarás
 - Por Qué Te Vas
 - ni de ti
 - Te Pido
 - ángel
 - Acércate
 - Si Tu Te Vas
 - Princesa
 - Te Quiero Más
 - Missed Calls
 - El Último Beso
 - 22
 - Quiero Volver
 - Te Creo
 - No Reply
 - Confía En Mí
 - Una Noche Más LIVE
 - Yo Te Amo A Ti
 - De Papel
 - Down
 - buenos aires en vivo
 - Te Creo LIVE
 - Recuerdo
 - me voy
 - Ya No Hay Nadie Que Nos Pare
 - What If, Then What? (feat. Amiture)
 - Se Escapa Tu Amor
 - Te Olvidaré
 - Ella Dice
 - Ser Mejor
 - buenos aires
 - posta
 - tinta 90
 - Great Escape
 - My Stupid Heart
 - Duele (feat. John C)
 - miedo
 - Beso En Las Rocas
 - 7 Veces
 - Aquí Estoy
 - pa en vivo
 - ángel en vivo
 - bien
 - Diciembre
 - Tuyo
 - ellas

#### Consulta en album, por id artista

In [101]:
import requests
import time

def consulta_album():
    #lista_id=[12246, 246791, 7188840, 525046, 4050205, 5531258, 71855892, 1194083, 9635624, 1562681, 10583405, 5297021, 12029862, 6705223, 11928391, 554792, 111130212, 2697, 2792, 70, 4902904, 14343187, 2252591, 13299379, 12268072, 5181388, 12637039, 160, 12487862, 61094422]
    lista_id1=[12246]
    #headers para evitar bloqueos
    #headers = {
    #    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    #}
 
    #album_search = {'id': [], 'title': [], 'rank': [], 'artist': []}
    resultado_album=[]
    #for i in lista_id1:
    url= f"https://api.deezer.com/artist/12246/top?limit=100"
    print(f"Consultando album para: {lista_id1}")
    
    respuesta = requests.get(url)#, headers=headers)
    if respuesta.status_code != 200:
        print(f"Error {respuesta.status_code} para {lista_id1}")
    datos = respuesta.json()
    resultado_album=datos['data'][0]
    return resultado_album

In [102]:
a=consulta_album()

Consultando album para: [12246]

In [103]:
print(json.dumps(a,indent=2,ensure_ascii=False))

{
  "id": 3579685431,
  "readable": true,
  "title": "The Fate of Ophelia",
  "title_short": "The Fate of Ophelia",
  "title_version": "",
  "link": "https://www.deezer.com/track/3579685431",
  "duration": 226,
  "rank": 999852,
  "explicit_lyrics": false,
  "explicit_content_lyrics": 0,
  "explicit_content_cover": 2,
  "preview": "https://cdnt-preview.dzcdn.net/api/1/1/0/4/9/0/049e295c37bff556879080a0ec19adb3.mp3?hdnea=exp=1777039548~acl=/api/1/1/0/4/9/0/049e295c37bff556879080a0ec19adb3.mp3*~data=user_id=0,application_id=42~hmac=22df25dd08e0e422804b3f604fb038d5f4dfe46727fb8041381e36708e4a9c9e",
  "contributors": [
    {
      "id": 12246,
      "name": "Taylor Swift",
      "link": "https://www.deezer.com/artist/12246",
      "share": "https://www.deezer.com/artist/12246?utm_source=deezer&utm_content=artist-12246&utm_term=0_1777038648&utm_medium=web",
      "picture": "https://api.deezer.com/artist/12246/image",
      "picture_small": "https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/56x56-000000-80-0-0.jpg",
      "picture_medium": "https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/250x250-000000-80-0-0.jpg",
      "picture_big": "https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/500x500-000000-80-0-0.jpg",
      "picture_xl": "https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/1000x1000-000000-80-0-0.jpg",
      "radio": true,
      "tracklist": "https://api.deezer.com/artist/12246/top?limit=50",
      "type": "artist",
      "role": "Main"
    }
  ],
  "md5_image": "d0bed55a0efb3c5c3ddb3dacda67d9b3",
  "artist": {
    "id": 12246,
    "name": "Taylor Swift",
    "tracklist": "https://api.deezer.com/artist/12246/top?limit=50",
    "type": "artist"
  },
  "album": {
    "id": 829966251,
    "title": "The Life of a Showgirl",
    "cover": "https://api.deezer.com/album/829966251/image",
    "cover_small": "https://cdn-images.dzcdn.net/images/cover/d0bed55a0efb3c5c3ddb3dacda67d9b3/56x56-000000-80-0-0.jpg",
    "cover_medium": "https://cdn-images.dzcdn.net/images/cover/d0bed55a0efb3c5c3ddb3dacda67d9b3/250x250-000000-80-0-0.jpg",
    "cover_big": "https://cdn-images.dzcdn.net/images/cover/d0bed55a0efb3c5c3ddb3dacda67d9b3/500x500-000000-80-0-0.jpg",
    "cover_xl": "https://cdn-images.dzcdn.net/images/cover/d0bed55a0efb3c5c3ddb3dacda67d9b3/1000x1000-000000-80-0-0.jpg",
    "md5_image": "d0bed55a0efb3c5c3ddb3dacda67d9b3",
    "tracklist": "https://api.deezer.com/album/829966251/tracks",
    "type": "album"
  },
  "type": "track"
}