#### Consulta en last.fm API

Librerias

In [ ]:
import requests
import json
import pandas as pd
import time

Universo bajo : 30 artistas, se consulta a la API last.fm biografia, estadisticas y artistas similares.

In [ ]:
lista_artistas=[
 
    # 🇺🇸 EEUU (10)
    "Taylor Swift", "Drake", "Morgan Wallen", "Kendrick Lamar", "The Weeknd",
    "SZA", "Zach Bryan", "Tyler the Creator", "Billie Eilish", "Ariana Grande",
 
    # 🇪🇸 España (10)
    "Bad Bunny", "Karol G", "Myke Towers", "Quevedo", "Aitana",
    "Rosalía", "Morad", "Melendi", "Enrique Iglesias", "Juanes",
 
    # 🇦🇷 Argentina (10)
    "Duki", "María Becerra", "Tini Stoessel", "Nicki Nicole", "Cazzu",
    "Lali", "Paulo Londra", "Shakira", "Bizarrap", "Emilia",
]
 
print(f"Total: {len(lista_artistas)} artistas ✅")

API Key

In [ ]:
apikey= "48703fdebfcfe72db0d901a30cf4af31"

#### Consulta preliminar:
Biografía del Artista. Popularidad y Estadísticas de Reproducción. Artistas Similares.

In [27]:
def consulta_info_artista():    #consulta de biografias, campo completo, -not 'summary'
    
    apikey= "48703fdebfcfe72db0d901a30cf4af31"
    
    lista_artistas=["Taylor Swift", "Drake", "Morgan Wallen", "Kendrick Lamar", "The Weeknd",
    "SZA", "Zach Bryan", "Tyler the Creator", "Billie Eilish", "Ariana Grande", "Bad Bunny", 
    "Karol G", "Myke Towers", "Quevedo", "Aitana","Rosalía", "Morad", "Melendi", "Enrique Iglesias",
    "Juanes", "Duki", "María Becerra", "Tini Stoessel", "Nicki Nicole", "Cazzu","Lali", 
    "Paulo Londra", "Shakira", "Bizarrap", "Emilia"]
    
    datos=[]

    for artista in lista_artistas:
        url=f"https://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist={artista}&api_key={apikey}&format=json"
        respuesta=requests.get(url)
        respuesta.status_code

        if respuesta.status_code != 200:
            print (f"Error al consultar {artista}: {respuesta.status_code}.")
        
        info_artista=respuesta.json()
        datos.append({'artista': artista, 'biografia': info_artista['artist']['bio']['content']})
        

    return datos

In [42]:
bio=consulta_info_artista()

In [50]:
df_bio=pd.DataFrame(bio)
df_bio.head(5)

          artista                                          biografia
0    Taylor Swift  Taylor Alison Swift is an American singer-song...
1           Drake  Aubrey "Drake" Graham (born October 24, 1986) ...
2   Morgan Wallen  Morgan Wallen sets the pace in, and beyond, co...
3  Kendrick Lamar  Kendrick Lamar Duckworth (born June 17, 1987) ...
4      The Weeknd  Abel Makkonen Tesfaye (born February 16, 1990)...

'artist' {'similar':{'artist':[{name:'sabrina'},...}, {'name: 'taylor'}]}......},{},.. // 
'bio' -> 'summary' o 'content' 
'tags' -->{'tag':[{'name': 'pop', 'url': 'https://www.last.fm/tag/pop'},
     {'name': 'female vocalists',
      'url': 'https://www.last.fm/tag/female+vocalists'},
     {'name': 'swedish', 'url': 'https://www.last.fm/tag/swedish'},
     {'name': '90s', 'url': 'https://www.last.fm/tag/90s'},
     {'name': 'argentina', 'url': 'https://www.last.fm/tag/argentina'}]},
   'bio': {'links': {'link': {'#text': '', 'rel': 'original',
      'href': 'https://last.fm/music/Emilia/+wiki'}},
    'published': '11 Aug 2006, 21:27',
    'summary': 'María Emilia Mernes, better known as Emilia, is an Argentine singer, actress and model born on October 29, 1996 in the town of Nogoyá, Entre Ríos.\n\nFrom a very young age she showed a great interest in music, participating in local events and contests. In 2016, Emilia, along with Fer Vázquez, joined the Uruguayan cumbia pop group, Rombai, thus making a place for herself on the scene. She decided in 2018 to leave the group to launch her solo career. <a href="https://www.last.fm/music/Emilia">Read more on Last.fm</a>',
    'content':María Emilia Mernes, better known as Emilia, is an Argentine singer, actress and model born on October 29, 1996 in the town of Nogoyá, Entre Ríos.\n\nFrom a very young age she showed a great interest in music, participating in local events and contests. In 2016, Emilia, along with Fer Vázquez, joined the Uruguayan cumbia pop group, Rombai, thus making .....SIGUE SIGUE
    }}}]

In [63]:
def consulta_stats_artista():
    
    apikey= "48703fdebfcfe72db0d901a30cf4af31"
    
    lista_artistas=["Taylor Swift", "Drake", "Morgan Wallen", "Kendrick Lamar", "The Weeknd",
    "SZA", "Zach Bryan", "Tyler the Creator", "Billie Eilish", "Ariana Grande", "Bad Bunny", 
    "Karol G", "Myke Towers", "Quevedo", "Aitana","Rosalía", "Morad", "Melendi", "Enrique Iglesias",
    "Juanes", "Duki", "María Becerra", "Tini Stoessel", "Nicki Nicole", "Cazzu","Lali", 
    "Paulo Londra", "Shakira", "Bizarrap", "Emilia"]
    
    datos=[]

    for artista in lista_artistas:
        url=f"https://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist={artista}&api_key={apikey}&format=json"
        respuesta=requests.get(url)
        respuesta.status_code

        if respuesta.status_code != 200:
            print (f"Error al consultar {artista}: {respuesta.status_code}.")
        
        info_artista=respuesta.json()
        datos.append({'artista': artista, 'n_oyentes': info_artista['artist']['stats']['listeners'], 'n_playcount': info_artista['artist']['stats']['playcount']})
        

    return datos

In [64]:
stats=consulta_stats_artista()

In [65]:
df_stats=pd.DataFrame(stats)
df_stats.head(5)

          artista n_oyentes n_playcount
0    Taylor Swift   5940154  3676774009
1           Drake   6720593  1165340486
2   Morgan Wallen    986477    91475832
3  Kendrick Lamar   5098105  1031584717
4      The Weeknd   5318620  1123047548

In [67]:
df_stats.to_csv('artistas_stats.csv',index=False)

In [ ]:
def consulta_similar_artista():
    
    apikey= "48703fdebfcfe72db0d901a30cf4af31"
    
    lista_artistas=["Taylor Swift", "Drake", "Morgan Wallen", "Kendrick Lamar", "The Weeknd",
    "SZA", "Zach Bryan", "Tyler the Creator", "Billie Eilish", "Ariana Grande", "Bad Bunny", 
    "Karol G", "Myke Towers", "Quevedo", "Aitana","Rosalía", "Morad", "Melendi", "Enrique Iglesias",
    "Juanes", "Duki", "María Becerra", "Tini Stoessel", "Nicki Nicole", "Cazzu","Lali", 
    "Paulo Londra", "Shakira", "Bizarrap", "Emilia"]
    
    datos=[]

    for artista in lista_artistas:
        url=f"https://ws.audioscrobbler.com/2.0/?method=artist.getsimilar&artist={artista}&api_key={apikey}&format=json"
        respuesta=requests.get(url)
        respuesta.status_code

        if respuesta.status_code != 200:
            print (f"Error al consultar {artista}: {respuesta.status_code}.")
        
        info_artista=respuesta.json()

        similares = info_artista.get("similarartists", {}).get("artist", [])

        for similar in similares:
            datos.append({"artista": artista, "similar": similar.get("name")})


    return datos

In [94]:
similar_artistas=consulta_similar_artista()

In [95]:
df_similar_artistas=pd.DataFrame(similar_artistas)
df_similar_artistas.head(5)

        artista            similar
0  Taylor Swift  Sabrina Carpenter
1  Taylor Swift     Olivia Rodrigo
2  Taylor Swift      Gracie Abrams
3  Taylor Swift       Harry Styles
4  Taylor Swift      Chappell Roan

In [96]:
df_similar_artistas.to_csv('artistas_similares.csv',index=False)